### ISSUE TITLE
wal-g push failing with out of memory

### ISSUE THREAD

**Issue by sumedhpathak** [wal-g/wal-g#1111]
### Database name
PostgreSQL

# Issue description
Wal-g in wal-push mode seems to start eating a lot of memory for each file, and ultimately fails with an out-of-memory error.

### Describe your problem
// here is your problem

### Please provide steps to reproduce
// it can really help

### Please add config and wal-g stdout/stderr logs for debug purpose

```

fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x1c4a9e1, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc100000000, 0x4000000, 0x33ef798)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x33d4e40, 0x4000000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x33d4e40, 0x2000, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x33d4e40, 0x2000, 0x33ef7a8, 0x2d5a060)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x33d4e40, 0x2000, 0x101, 0x7fc90e977de8)

```

We have updated VM overcommit, and there seems to be sufficient swap available. It's unclear why wal-g is taking that much memory for each wal-file.

**Comment by rongxunwang** [comment]
Output of wal-g --version: 
wal-g version   e6c2090 2021.10.01_21:13:49     PostgreSQL

Can you elaborate a bit the WAL-G configuration file you are asking? Where can I find it? I am not aware of any config file we use for wal-g. Thanks!

**Comment by rongxunwang** [comment]
wal-g stopped working after the OOM issue. Below is the output of "free -h":

```
              total        used        free      shared  buff/cache   available
Mem:           7.6G        4.0G        931M         16M        2.7G        3.3G
Swap:          2.5G         81M        2.4G
```

When we executed the wal-g directly as "../bin/wal-g wal-push ../pg_wal/xxxx", it failed with callstack below:

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1c4a9e1, 0x16)
        /usr/local/go/src/runtime/panic.go:774 +0x72
runtime.sysMap(0xc058000000, 0x4000000, 0x33ef798)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x33d4e40, 0x4000000, 0x0, 0x203000)
        /usr/local/go/src/runtime/malloc.go:701 +0x1cd
runtime.(*mheap).grow(0x33d4e40, 0x2000, 0xffffffff)
        /usr/local/go/src/runtime/mheap.go:1255 +0xa3
runtime.(*mheap).allocSpanLocked(0x33d4e40, 0x2000, 0x33ef7a8, 0x2d5a060)
        /usr/local/go/src/runtime/mheap.go:1170 +0x266
runtime.(*mheap).alloc_m(0x33d4e40, 0x2000, 0x101, 0x7f418ec7dde8)
        /usr/local/go/src/runtime/mheap.go:1022 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1093 +0x4c
runtime.(*mheap).alloc(0x33d4e40, 0x2000, 0xc000010101, 0xc000000d80)
        /usr/local/go/src/runtime/mheap.go:1092 +0x8a
runtime.largeAlloc(0x4000000, 0x101, 0xc000232d80)
        /usr/local/go/src/runtime/malloc.go:1138 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1033 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1146

goroutine 51 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330
runtime.mallocgc(0x4000000, 0x1814900, 0xc000232d01, 0x10ff883)
        /usr/local/go/src/runtime/malloc.go:1032 +0x895
runtime.makeslice(0x1814900, 0x4000000, 0x4000000, 0xc05382a000)
        /usr/local/go/src/runtime/slice.go:49 +0x6c
github.com/Azure/azure-storage-blob-go/azblob.NewStaticBuffer(0x4000000, 0x3, 0x41, 0x0, 0x0, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:410 +0xf5
github.com/Azure/azure-storage-blob-go/azblob.(*UploadStreamToBlockBlobOptions).defaults(0xc000cf76a0, 0xc0003301c0, 0x5)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:533 +0x67
github.com/Azure/azure-storage-blob-go/azblob.UploadStreamToBlockBlob(0x203a2e0, 0xc0000d2030, 0x1fe97a0, 0xc00000e3a0, 0xc0003301c0, 0x5, 0x0, 0x0, 0x0, 0xc0003301c8, ...)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:544 +0x56
github.com/wal-g/wal-g/pkg/storages/azure.(*Folder).PutObject(0xc00000c780, 0xc000253a20, 0x1c, 0x1fe97a0, 0xc00000e3a0, 0xc000253a39, 0xc000086c58)
        /home/username/var/go/src/github.com/wal-g/wal-g/pkg/storages/azure/folder.go:216 +0x2d0
github.com/wal-g/wal-g/internal.(*Uploader).Upload(0xc000112700, 0xc000253a20, 0x1c, 0x1ff90e0, 0xc0000d60d0, 0x1c, 0x3)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/uploader.go:136 +0x89
github.com/wal-g/wal-g/internal.(*Uploader).UploadFile(0xc000112700, 0x2007860, 0xc00000e1a0, 0x1ff96e0, 0xc0000d60c8)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/uploader.go:115 +0x229
github.com/wal-g/wal-g/internal/databases/postgres.(*WalUploader).UploadWalFile(0xc000ff5f18, 0x2009e60, 0xc0000d60c8, 0x0, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_uploader.go:63 +0x206
github.com/wal-g/wal-g/internal/databases/postgres.uploadWALFile(0xc000ff5f18, 0xc0000ce0f0, 0x2c, 0xc0000ce000, 0x2c, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_push_handler.go:88 +0x14b
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).upload(0xc000ff2070, 0xc001000393, 0x1e, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:217 +0x261
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).processFiles.func1(0xc000ff2070, 0xc001000393, 0x1e, 0xc0002d0070)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:195 +0x43
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1
created by github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).processFiles
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:194 +0x192

goroutine 1 [runnable]:
io.(*pipe).Read(0xc0002eb040, 0xc00100400b, 0x3fffff5, 0x3fffff5, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:53 +0x144
io.(*PipeReader).Read(0xc000010948, 0xc00100400b, 0x3fffff5, 0x3fffff5, 0x4, 0x0, 0x0)
        /usr/local/go/src/io/pipe.go:127 +0x4c
github.com/wal-g/wal-g/internal.(*WithSizeReader).Read(0xc000f8b580, 0xc00100400b, 0x3fffff5, 0x3fffff5, 0x4, 0x0, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/with_size_reader.go:18 +0x51
io.ReadAtLeast(0x1fe97a0, 0xc000f8b580, 0xc001004000, 0x4000000, 0x4000000, 0x4000000, 0xc0008df880, 0x7f419236c008, 0x0)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/Azure/azure-storage-blob-go/azblob.(*copier).sendChunk(0xc000173a00, 0xc000173a00, 0xc0000d89c0)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/chunkwriting.go:127 +0xcf
github.com/Azure/azure-storage-blob-go/azblob.copyFromReader(0x203a2a0, 0xc0000ef140, 0x1fe97a0, 0xc000f8b580, 0x200a420, 0xc0000e0900, 0x203ae60, 0xc00000e500, 0x1, 0x4000000, ...)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/chunkwriting.go:53 +0x278
github.com/Azure/azure-storage-blob-go/azblob.UploadStreamToBlockBlob(0x203a2e0, 0xc0000d2030, 0x1fe97a0, 0xc000f8b580, 0xc0003301c0, 0x5, 0x0, 0x0, 0x0, 0xc0003301c8, ...)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/Azure/azure-storage-blob-go/azblob/highlevel.go:553 +0x130
github.com/wal-g/wal-g/pkg/storages/azure.(*Folder).PutObject(0xc00000c780, 0xc000ff0e60, 0x1c, 0x1fe97a0, 0xc000f8b580, 0xc000ff0e79, 0xc000f1d940)
        /home/username/var/go/src/github.com/wal-g/wal-g/pkg/storages/azure/folder.go:216 +0x2d0
github.com/wal-g/wal-g/internal.(*Uploader).Upload(0xc000ff2000, 0xc000ff0e60, 0x1c, 0x1ff90e0, 0xc000010948, 0x1c, 0x3)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/uploader.go:136 +0x89
github.com/wal-g/wal-g/internal.(*Uploader).UploadFile(0xc000ff2000, 0x2007860, 0xc000f8b500, 0x1ff96e0, 0xc000010940)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/uploader.go:115 +0x229
github.com/wal-g/wal-g/internal/databases/postgres.(*WalUploader).UploadWalFile(0xc000fdb420, 0x2009e60, 0xc000010940, 0x0, 0x0)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_uploader.go:63 +0x206
github.com/wal-g/wal-g/internal/databases/postgres.uploadWALFile(0xc000fdb420, 0x7ffef9343566, 0x2c, 0xc000fdb400, 0x0, 0xc000ff2070)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_push_handler.go:88 +0x14b
github.com/wal-g/wal-g/internal/databases/postgres.HandleWALPush(0xc000fdb420, 0x7ffef9343566, 0x2c)
        /home/username/var/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_push_handler.go:60 +0x464
github.com/wal-g/wal-g/cmd/pg.glob..func11(0x329bf00, 0xc000fa85e0, 0x1, 0x1)
        /home/username/var/go/src/github.com/wal-g/wal-g/cmd/pg/wal_push.go:38 +0x28c
github.com/spf13/cobra.(*Command).execute(0x329bf00, 0xc000fa85a0, 0x1, 0x1, 0x329bf00, 0xc000fa85a0)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x329b780, 0x44d3ea, 0x32b3a20, 0xc000000180)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/username/var/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/username/var/go/src/github.com/wal-g/wal-g/cmd/pg/pg.go:42 +0x36
main.main()
        /home/username/var/go/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

**Comment by serprex** [comment]
Update: testing with #1135 is showing a much better memory profile
