### ISSUE TITLE
Wal-g crashes when running backup-push

### ISSUE THREAD

**Issue by plaes** [wal-g/wal-g#120]
Wal-g v0.1.12.
Running into following crash when trying to create basebackup (seems similar to #55 although the target directory is not symlink):
```
PGHOST=/var/run/postgresql wal-g.sh backup-push /tmp/kala
BUCKET: XXX
SERVER: 
Walking ...
Starting part 1 ...

Finished writing part 1.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85c9ee]

goroutine 1 [running]:
github.com/wal-g/wal-g.(*Bundle).HandleSentinel(0xc42009a410, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/bundle.go:221 +0x3e
github.com/wal-g/wal-g.HandleBackupPush(0xc42035ca75, 0x9, 0xc420645a00, 0xc42011a8a0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/commands.go:422 +0x65b
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:138 +0x6b7
```

**Comment by x4m** [comment]
Hi!
While this bug may seem unharmful, I suspect there may be other related problems with pre 9.6 backups. I'll investigate it more and probably will fix eventually. Thanks for reporting!

**Comment by kratorman** [comment]
@x4m I have same issue.
postgres: 10.5
Wal-g 0.1.15

**Comment by combrs** [comment]
I'm try to use $ wal-g -v
v0.2.4

And when run backup-push, I was mixed up  source and destination parameter, and result command was like this:
WALG_FILE_PREFIX=/srv/wal_archive/ wal-g backup-push /srv/wal_archive/

Output is (pause for FIVE minutes)
Path:  
INFO: 2019/02/06 16:36:22.926322 Doing full backup.
INFO: 2019/02/06 16:36:23.044460 Walking ...
INFO: 2019/02/06 16:36:23.045383 Starting part 1 ...
INFO: 2019/02/06 16:41:14.061580 Finished writing part 1.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbaba9b]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc00038e000, 0xea3da5, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:350 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0x7ffffa8206e8, 0x11, 0xc00010b800)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:126 +0x617
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:133 +0x625

Real backup-push on this base takes 10 seconds:

-bash-4.2$ ./make_basebackup.sh $PGDATA
Path:  
INFO: 2019/02/06 16:51:27.366282 Doing full backup.
INFO: 2019/02/06 16:51:27.482809 Walking ...
INFO: 2019/02/06 16:51:27.483182 Starting part 1 ...
INFO: 2019/02/06 16:51:37.162901 Finished writing part 1.
INFO: 2019/02/06 16:51:37.325504 Starting part 2 ...
INFO: 2019/02/06 16:51:37.331159 /global/pg_control
INFO: 2019/02/06 16:51:37.334278 Finished writing part 2.
INFO: 2019/02/06 16:51:37.336412 Starting part 3 ...
INFO: 2019/02/06 16:51:37.347241 backup_label
INFO: 2019/02/06 16:51:37.347272 tablespace_map
INFO: 2019/02/06 16:51:37.347884 Finished writing part 3.
INFO: 2019/02/06 16:51:37.392482 Uploaded 3 compressed tar Files.

Can you fix it, by immediately exit with error (for example), when WALG_FILE_PREFIX == destdir cmdline parameter? Current SIGSEGV message is not seems "more clear" ...
I understand : it is unusual when WALG_FILE_PREFIX == destdir , but I not set it at all and got 
"usage:	wal-g backup-push backup_directory"

What is a "backup directory" ? it is source or destination? I think it is destination ... (source are hidden in my shell script)

**Comment by x4m** [comment]
Yes, this definitely should be fixed.

**Comment by Zhen-hao** [comment]
I am trying to use Wal-g to backup to local files but am very confused by the semantics of the argument of `backup-push`.
If we are supposed to pass the output path, what's the point of requiring `WALG_FILE_PREFIX`? 
I can't find documentation about what to pass to `backup-push`.
