### ISSUE TITLE
libsodium decryption panics (index out of range [0] with length 0)

### ISSUE THREAD

**Issue by joelbohnes** [wal-g/wal-g#1226]
### Database name
PostgreSQL

# Issue description
libsodium decryption panics.

### Describe your problem
Backup restoration fails when using libsodium encryption. 

### Steps to reproduce
0) Create a backup
1) Restore a backup (i.e. wal-g backup-restore /tmp/foo LATEST)

### Output
```bash
# wal-g backup-restore ... ...
panic: runtime error: index out of range [0] with length 0

goroutine 84 [running]:
github.com/wal-g/wal-g/internal/crypto/libsodium.(*Reader).readNextChunk(0xc001393680)
        /build/internal/crypto/libsodium/reader.go:108 +0x40f
github.com/wal-g/wal-g/internal/crypto/libsodium.(*Reader).Read(0xc001393680, {0xc000550a20, 0x4, 0xc001393680})
        /build/internal/crypto/libsodium/reader.go:78 +0xb7
io.ReadAtLeast({0x1ae30c0, 0xc001393680}, {0xc000550a20, 0x4, 0xf}, 0x4)
        /usr/local/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
        /usr/local/go/src/io/io.go:347
github.com/pierrec/lz4/v4/internal/lz4stream.(*Frame).readUint32(0xc000550a20, {0x1ae30c0, 0xc001393680})
        /go/pkg/mod/github.com/pierrec/lz4/v4@v4.1.11/internal/lz4stream/block.go:343 +0x45
github.com/pierrec/lz4/v4/internal/lz4stream.(*Frame).CloseR(0xc000550a20, {0x1ae30c0, 0xc001393680})
        /go/pkg/mod/github.com/pierrec/lz4/v4@v4.1.11/internal/lz4stream/frame.go:124 +0x55
github.com/pierrec/lz4/v4.(*Reader).Read(0xc00144c140, {0xc0013d0000, 0x14d29c0, 0x11a6201})
        /go/pkg/mod/github.com/pierrec/lz4/v4@v4.1.11/reader.go:133 +0x54e
github.com/wal-g/wal-g/internal.readTrailingZeros({0x7f8d3c14d968, 0xc00144a240})
        /build/internal/extract.go:253 +0x62
github.com/wal-g/wal-g/internal.extractFile({0x1ae3120, 0xc000bba210}, {0x7f8d3c14d968, 0xc00144a240}, {0x1b138b8, 0xc000bc0fc0})
        /build/internal/extract.go:181 +0xcf
github.com/wal-g/wal-g/internal.tryExtractFiles.func1()
        /build/internal/extract.go:222 +0x247
created by github.com/wal-g/wal-g/internal.tryExtractFiles
        /build/internal/extract.go:210 +0x30f
```
### Config
```
WALG_GS_PREFIX=gs://my-bucket/my-folder
GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcs-credentials
WALG_LIBSODIUM_KEY=0000000000000000000000000000000000000000000000000000000000000000
WALG_LIBSODIUM_KEY_TRANSFORM=hex
PGHOST=127.0.0.1
PGPORT=5432
PGUSER=postgres
PGPASS=mysecretpassword
```

**Comment by joelbohnes** [comment]
Git bisect result:
```bash
$ git bisect log
git bisect start
# good: [05d04a3b47d382624905deaa03ab1241e1dbe77d] libsodium: fix OOB read, add transforms (fixes #1086) (#1087)
git bisect good 05d04a3b47d382624905deaa03ab1241e1dbe77d
# bad: [e904ad9a5716e525f35ac6f093c15f3649c68b66] Bump golangci/golangci-lint-action from 2.5.2 to 3.1.0 (#1225)
git bisect bad e904ad9a5716e525f35ac6f093c15f3649c68b66
# bad: [ba82cf3e1df607893463a2abeb9c5f601ce7548e] Fix greenplum backup-fetch by user data (#1204)
git bisect bad ba82cf3e1df607893463a2abeb9c5f601ce7548e
# bad: [def83ac469b47e44c6c5769c0de321a7c9669a1e] Merge pull request #1181 from citusdata/decompression-is-reader
git bisect bad def83ac469b47e44c6c5769c0de321a7c9669a1e
# good: [5a339192812295506fb036677e5b4ad65ea72b3f] Add metadata datetime format to backup sentinel (#1185)
git bisect good 5a339192812295506fb036677e5b4ad65ea72b3f
# good: [ddef0673b9262c08b93c712b598922f18d9d18d6] fixing naming in IsLogAlreadyApplied
git bisect good ddef0673b9262c08b93c712b598922f18d9d18d6
# skip: [a609be7e6a2d0d11241a9b277bc0cc1973d7f22a] DecryptAndDecompressTar: return ReadCloser instead of taking Writer
git bisect skip a609be7e6a2d0d11241a9b277bc0cc1973d7f22a
# good: [b66792275827be852ed2f257cc952f8c2d9177ea] Merge pull request #1189 from trootnev/master
git bisect good b66792275827be852ed2f257cc952f8c2d9177ea
# only skipped commits left to test
# possible first bad commit: [def83ac469b47e44c6c5769c0de321a7c9669a1e] Merge pull request #1181 from citusdata/decompression-is-reader
# possible first bad commit: [a609be7e6a2d0d11241a9b277bc0cc1973d7f22a] DecryptAndDecompressTar: return ReadCloser instead of taking Writer
```

Commit a609be7e6a2d0d11241a9b277bc0cc1973d7f22a was skipped because it fails with a different error:
```bash
# wal-g backup-fetch /tmp/foo LATEST
INFO: 2022/02/28 10:25:20.614355 Selecting the latest backup...
INFO: 2022/02/28 10:25:20.847077 LATEST backup is: 'base_000000010000000000000005'
INFO: 2022/02/28 10:25:21.124512 Finished extraction of part_001.tar.lz4
ERROR: 2022/02/28 10:25:21.124574 Extraction error in part_001.tar.lz4: extractOne: tar extract failed: corrupted chunk
```
