### ISSUE TITLE
check-ao-aocs-length command does not read config

### ISSUE THREAD

**Issue by eshkinkot** [wal-g/wal-g#1663]
### Database name
Greenplum

wal-g check-ao-aocs-length command does not support wal-g config.

### Describe your problem
```
gpadmin@master:~$ wal-g --config ~/.walg.yaml check-ao-aocs-length
panic: Cannot create log directory /var/log/greenplum: mkdir /var/log/greenplum: permission denied

goroutine 1 [running]:
github.com/greenplum-db/gp-common-go-libs/gplog.abort({0xc000ebfbf0?, 0x1?, 0x1?})
        /home/runner/work/wal-g/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:353 +0x45
github.com/greenplum-db/gp-common-go-libs/gplog.createLogDirectory({0x2201afc, 0x12})
        /home/runner/work/wal-g/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:370 +0x146
github.com/greenplum-db/gp-common-go-libs/gplog.InitializeLogging({0x21eef97, 0x5}, {0x2201afc, 0x12})
        /home/runner/work/wal-g/wal-g/vendor/github.com/greenplum-db/gp-common-go-libs/gplog/gplog.go:118 +0xf7
github.com/wal-g/wal-g/internal/databases/greenplum.initGpLog({0x2201afc?, 0x0?})
        /home/runner/work/wal-g/wal-g/internal/databases/greenplum/configure.go:40 +0x5c
github.com/wal-g/wal-g/internal/databases/greenplum.NewAOLengthCheckHandler(...)
        /home/runner/work/wal-g/wal-g/internal/databases/greenplum/ao_check_length_handler.go:22
github.com/wal-g/wal-g/cmd/gp.glob..func6(0x3befb60?, {0xc000237820?, 0x0?, 0x2?})
        /home/runner/work/wal-g/wal-g/cmd/gp/check_ao_length.go:20 +0x58
github.com/spf13/cobra.(*Command).execute(0x3befb60, {0xc0002377a0, 0x2, 0x2})
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x3beec60)
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
github.com/wal-g/wal-g/cmd/gp.Execute()
        /home/runner/work/wal-g/wal-g/cmd/gp/gp.go:45 +0x25
main.main()
        /home/runner/work/wal-g/wal-g/main/gp/main.go:8 +0x17
```

```
gpadmin@master:~$ grep LOG ~/.walg.yaml
WALG_GP_LOGS_DIR: /home/gpadmin/gpAdminLogs
```

**Comment by debebantur** [comment]
Hello!
Thank you for your report, I made fixes in pr above. Also you can fix this issue by adding directory with --logs flag to command.
