### ISSUE TITLE
wal-g v3.0.3 on oraclelinux8 runtime error

### ISSUE THREAD

**Issue by holubnychyi** [wal-g/wal-g#1811]
### Database name
Postgresql

# Issue description
After successfully building new version wal-g v3.0.3 in oraclelinux8.

```
export USE_LIBSODIUM=1
export USE_LZO=1
export GOPATH="/root/go"
export GOBIN="/root/go/bin"

dnf -y install \
    cmake \
    gcc gcc-c++ \
    lzo-devel

wget https://go.dev/dl/go1.22.8.linux-amd64.tar.gz -O /root/go1.22.8.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf /root/go1.22.8.linux-amd64.tar.gz

git clone https://github.com/wal-g/wal-g $(go env GOPATH)/src/github.com/wal-g/wal-g
cd $GOPATH/src/github.com/wal-g/wal-g
git checkout tags/v3.0.3 -b v3.0.3

mkdir tmp && wget https://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz -O tmp/lzo-2.10.tar.gz && \
mkdir -p tmp/lzo && tar -xzf tmp/lzo-2.10.tar.gz -C tmp/lzo
cd tmp/lzo/lzo-2.10 && ./configure && make && make install

cd $GOPATH/src/github.com/wal-g/wal-g
make deps && \
make pg_build`

```
### Describe your problem
Some commands executed without issues, for example wal-g --version, wal-g st ls wal_005.
```
# wal-g --version
wal-g version v3.0.3    3f88f3ca        2024.10.17_15:29:31     PostgreSQL
```

If I execute backup commands like backup-list, backup-push, I get the runtime error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/wal-g/wal-g/pkg/storages/gcs.(*Folder).joinPath(0x7fb5bddf85b8?, {0xc00012daf0?, 0xc00007d008?}, {0x2582288?, 0x0?})
	/root/go/src/github.com/wal-g/wal-g/pkg/storages/gcs/folder.go:253 +0xcd
github.com/wal-g/wal-g/pkg/storages/gcs.(*Folder).GetSubFolder(0xc0008ffb80, {0x2582288?, 0x20c57b9?})
	/root/go/src/github.com/wal-g/wal-g/pkg/storages/gcs/folder.go:133 +0x35
github.com/wal-g/wal-g/internal/multistorage.UseAllAliveStorages({0x25bfc08?, 0xc00045cbd0?})
	/root/go/src/github.com/wal-g/wal-g/internal/multistorage/folder.go:37 +0x1f5
github.com/wal-g/wal-g/cmd/pg.init.func10(0x3e0f880?, {0x4080de0?, 0x0?, 0x0?})
	/root/go/src/github.com/wal-g/wal-g/cmd/pg/backup_list.go:32 +0x1f8
github.com/spf13/cobra.(*Command).execute(0x3e0f880, {0x4080de0, 0x0, 0x0})
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860 +0x684
github.com/spf13/cobra.(*Command).ExecuteC(0x3e0fd80)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
github.com/wal-g/wal-g/cmd/pg.Execute()
	/root/go/src/github.com/wal-g/wal-g/cmd/pg/pg.go:55 +0x1f
main.main()
	/root/go/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0xf

```

**Comment by x4m** [comment]
Hi! Thanks for letting us know, this is a bug.
I have no idea how come we use hand-written joinPath() at that place, but its implementation is buggy.
The workaround is easy, just remove trailing / in google cloud storage path.
Thanks!

**Comment by holubnychyi** [comment]
Thank you, it partly helped, I changed  GCS_NORMALIZE_PREFIX to default and backup is successfully completed.
backup-push, backup-fetch work fine.
And now I faced with the next issue during postgresql restore procedure, during backup DB WAL recovery:

```
SIGQUIT: quit
PC=0x4800a1 m=0 sigcode=0

goroutine 0 gp=0x40eae20 m=0 mp=0x40eba20 [idle]:
runtime.futex(0x40ebb60, 0x80, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/sys_linux_amd64.s:557 +0x21 fp=0x7ffef8184058 sp=0x7ffef8184050 pc=0x4800a1
runtime.futexsleep(0x7ffef81840d0?, 0x4157f0?, 0x1f8184100?)
	/usr/local/go/src/runtime/os_linux.go:69 +0x30 fp=0x7ffef81840a8 sp=0x7ffef8184058 pc=0x43fdb0
runtime.notesleep(0x40ebb60)
	/usr/local/go/src/runtime/lock_futex.go:170 +0x87 fp=0x7ffef81840e0 sp=0x7ffef81840a8 pc=0x415987
runtime.mPark(...)
	/usr/local/go/src/runtime/proc.go:1761
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:2782 +0x8c fp=0x7ffef8184110 sp=0x7ffef81840e0 pc=0x44aa6c
runtime.findRunnable()
	/usr/local/go/src/runtime/proc.go:3512 +0xd5f fp=0x7ffef8184288 sp=0x7ffef8184110 pc=0x44c5df
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:3868 +0xb1 fp=0x7ffef81842c0 sp=0x7ffef8184288 pc=0x44d6b1
runtime.goschedImpl(0xc0009b4540, 0x1)
	/usr/local/go/src/runtime/proc.go:4065 +0x178 fp=0x7ffef8184310 sp=0x7ffef81842c0 pc=0x44de38
runtime.gopreempt_m(0xc0009b4540?)
	/usr/local/go/src/runtime/proc.go:4082 +0x18 fp=0x7ffef8184330 sp=0x7ffef8184310 pc=0x44e078
runtime.mcall()
	/usr/local/go/src/runtime/asm_amd64.s:458 +0x4e fp=0x7ffef8184348 sp=0x7ffef8184330 pc=0x47c26e

goroutine 1 gp=0xc000006380 m=nil [select]:
runtime.gopark(0xc000865258?, 0x2?, 0x0?, 0x51?, 0xc00086522c?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc0008650d8 sp=0xc0008650b8 pc=0x4463ce
runtime.selectgo(0xc000865258, 0xc000865228, 0x0?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc0008651f8 sp=0xc0008650d8 pc=0x458205
io.(*pipe).read(0xc000522000, {0xc000b72c61, 0x308d39f, 0x7fcbe833b4b8?})
	/usr/local/go/src/io/pipe.go:57 +0xa5 fp=0xc000865288 sp=0xc0008651f8 pc=0x4c9f25
io.(*PipeReader).Read(0x3200000?, {0xc000b72c61?, 0xc000a00000?, 0x0?})
	/usr/local/go/src/io/pipe.go:134 +0x1a fp=0xc0008652b8 sp=0xc000865288 pc=0x4ca67a
github.com/wal-g/wal-g/utility.(*WithSizeReader).Read(0xc0000133f8, {0xc000b72c61?, 0x30ef6e0?, 0x30ef6e0?})
	/root/go/src/github.com/wal-g/wal-g/utility/with_size_reader.go:33 +0x28 fp=0xc0008652e8 sp=0xc0008652b8 pc=0x8bef28
github.com/wal-g/wal-g/pkg/storages/gcs.fillBuffer({0x25dfa80, 0xc0000133f8}, {0xc000a00000, 0x3200000, 0x3200000})
	/root/go/src/github.com/wal-g/wal-g/pkg/storages/gcs/folder.go:280 +0x90 fp=0xc000865320 sp=0xc0008652e8 pc=0x159cc90
github.com/wal-g/wal-g/pkg/storages/gcs.(*Folder).PutObjectWithContext(0xc0009c09c0, {0x260fde8, 0x414cfa0}, {0xc0000291a0, 0x1c}, {0x25dfa80, 0xc0000133f8})
	/root/go/src/github.com/wal-g/wal-g/pkg/storages/gcs/folder.go:173 +0x7d8 fp=0xc0008656a0 sp=0xc000865320 pc=0x159b258
github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectToFirst(...)
	/root/go/src/github.com/wal-g/wal-g/internal/multistorage/folder.go:450
github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectWithContext({{0x2611d40, 0xc0000133b0}, 0xc0002c2450, {0xc000460200, 0x1, 0x1}, {0xc0004ba320, 0x8}, {0x0, 0x0, ...}}, ...)
	/root/go/src/github.com/wal-g/wal-g/internal/multistorage/folder.go:433 +0xdc fp=0xc0008657d0 sp=0xc0008656a0 pc=0x8a155c
github.com/wal-g/wal-g/internal/multistorage.(*Folder).PutObjectWithContext(0x1c?, {0x260fde8?, 0x414cfa0?}, {0xc0000291a0?, 0x460e18?}, {0x25dfa80?, 0xc0000133f8?})
	<autogenerated>:1 +0xb0 fp=0xc0008658f0 sp=0xc0008657d0 pc=0x8a8d70
github.com/wal-g/wal-g/internal.(*RegularUploader).Upload(0xc0009c0940, {0x260fde8, 0x414cfa0}, {0xc0000291a0, 0x1c}, {0x25df760, 0xc000522000})
	/root/go/src/github.com/wal-g/wal-g/internal/uploader.go:178 +0x195 fp=0xc0008659e8 sp=0xc0008658f0 pc=0x171c515
github.com/wal-g/wal-g/internal.(*RegularUploader).UploadFile(0xc0009c0940, {0x260fde8, 0x414cfa0}, {0x2605f90, 0xc000460240})
	/root/go/src/github.com/wal-g/wal-g/internal/uploader.go:153 +0x23f fp=0xc000865ae0 sp=0xc0008659e8 pc=0x171c15f
github.com/wal-g/wal-g/internal/databases/postgres.(*WalUploader).UploadWalFile(0xc0009c0980, {0x260fde8, 0x414cfa0}, {0x2605fb8, 0xc00007e538})
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_uploader.go:69 +0x1ab fp=0xc000865b80 sp=0xc000865ae0 pc=0x18aaf6b
github.com/wal-g/wal-g/internal/databases/postgres.uploadWALFile({0x260fde8, 0x414cfa0}, 0xc0009c0980, {0x7ffef8185c87, 0x1f}, 0x80?)
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_push_handler.go:95 +0x10f fp=0xc000865bf8 sp=0xc000865b80 pc=0x18a27cf
github.com/wal-g/wal-g/internal/databases/postgres.HandleWALPush({0x260fde8, 0x414cfa0}, 0xc0009c0980, {0x7ffef8185c87, 0x1f})
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/wal_push_handler.go:60 +0x327 fp=0xc000865cd0 sp=0xc000865bf8 pc=0x18a2567
github.com/wal-g/wal-g/cmd/pg.init.func18(0x3edd020, {0xc0004a51a0, 0x1, 0x1?})
	/root/go/src/github.com/wal-g/wal-g/cmd/pg/wal_push.go:23 +0x179 fp=0xc000865d50 sp=0xc000865cd0 pc=0x18ce779
github.com/spf13/cobra.(*Command).execute(0x3edd020, {0xc0004a5180, 0x1, 0x1})
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860 +0x684 fp=0xc000865e40 sp=0xc000865d50 pc=0x5dc2e4
github.com/spf13/cobra.(*Command).ExecuteC(0x3edbea0)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974 +0x38d fp=0xc000865ef8 sp=0xc000865e40 pc=0x5dc92d
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
github.com/wal-g/wal-g/cmd/pg.Execute()
	/root/go/src/github.com/wal-g/wal-g/cmd/pg/pg.go:55 +0x1f fp=0xc000865f40 sp=0xc000865ef8 pc=0x18d16df
main.main()
	/root/go/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0xf fp=0xc000865f50 sp=0xc000865f40 pc=0x18d2c0f
runtime.main()
	/usr/local/go/src/runtime/proc.go:271 +0x29d fp=0xc000865fe0 sp=0xc000865f50 pc=0x445f7d
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000865fe8 sp=0xc000865fe0 pc=0x47e2a1

goroutine 2 gp=0xc000006e00 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00007afa8 sp=0xc00007af88 pc=0x4463ce
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:326 +0xb3 fp=0xc00007afe0 sp=0xc00007afa8 pc=0x446233
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00007afe8 sp=0xc00007afe0 pc=0x47e2a1
created by runtime.init.6 in goroutine 1
	/usr/local/go/src/runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000007340 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00007b780 sp=0xc00007b760 pc=0x4463ce
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.bgsweep(0xc0000a4000)
	/usr/local/go/src/runtime/mgcsweep.go:318 +0xdf fp=0xc00007b7c8 sp=0xc00007b780 pc=0x42fb9f
runtime.gcenable.gowrap1()
	/usr/local/go/src/runtime/mgc.go:203 +0x25 fp=0xc00007b7e0 sp=0xc00007b7c8 pc=0x4244a5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00007b7e8 sp=0xc00007b7e0 pc=0x47e2a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000007500 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x25d3f50?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00007bf78 sp=0xc00007bf58 pc=0x4463ce
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x40ea3c0)
	/usr/local/go/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00007bfa8 sp=0xc00007bf78 pc=0x42d549
runtime.bgscavenge(0xc0000a4000)
	/usr/local/go/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00007bfc8 sp=0xc00007bfa8 pc=0x42daf9
runtime.gcenable.gowrap2()
	/usr/local/go/src/runtime/mgc.go:204 +0x25 fp=0xc00007bfe0 sp=0xc00007bfc8 pc=0x424445
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00007bfe8 sp=0xc00007bfe0 pc=0x47e2a1
created by runtime.gcenable in goroutine 1
	/usr/local/go/src/runtime/mgc.go:204 +0xa5

goroutine 18 gp=0xc000104540 m=nil [finalizer wait]:
runtime.gopark(0xc00007a648?, 0x417645?, 0xa8?, 0x1?, 0xc000006380?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00007a620 sp=0xc00007a600 pc=0x4463ce
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:194 +0x107 fp=0xc00007a7e0 sp=0xc00007a620 pc=0x4234e7
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00007a7e8 sp=0xc00007a7e0 pc=0x47e2a1
created by runtime.createfing in goroutine 1
	/usr/local/go/src/runtime/mfinal.go:164 +0x3d

goroutine 19 gp=0xc000478540 m=nil [GC worker (idle)]:
runtime.gopark(0x1dadc588d07?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000076750 sp=0xc000076730 pc=0x4463ce
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000767e0 sp=0xc000076750 pc=0x426585
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x47e2a1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 20 gp=0xc000478700 m=nil [GC worker (idle)]:
runtime.gopark(0x1dadcfa576a?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000076f50 sp=0xc000076f30 pc=0x4463ce
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc000076fe0 sp=0xc000076f50 pc=0x426585
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000076fe8 sp=0xc000076fe0 pc=0x47e2a1
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/local/go/src/runtime/mgc.go:1234 +0x1c

goroutine 5 gp=0xc000478c40 m=nil [select]:
runtime.gopark(0xc000078778?, 0x3?, 0xb8?, 0x45?, 0xc000078772?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc000078618 sp=0xc0000785f8 pc=0x4463ce
runtime.selectgo(0xc000078778, 0xc00007876c, 0xc00018d000?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc000078738 sp=0xc000078618 pc=0x458205
go.opencensus.io/stats/view.(*worker).start(0xc00018d000)
	/root/go/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:276 +0x9f fp=0xc0000787c8 sp=0xc000078738 pc=0x152b39f
go.opencensus.io/stats/view.init.0.gowrap1()
	/root/go/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:34 +0x25 fp=0xc0000787e0 sp=0xc0000787c8 pc=0x152a745
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000787e8 sp=0xc0000787e0 pc=0x47e2a1
created by go.opencensus.io/stats/view.init.0 in goroutine 1
	/root/go/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:34 +0x8d

goroutine 9 gp=0xc000479340 m=nil [select]:
runtime.gopark(0xc00008dea0?, 0x2?, 0x20?, 0xdd?, 0xc00008de40?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00008dce8 sp=0xc00008dcc8 pc=0x4463ce
runtime.selectgo(0xc00008dea0, 0xc00008de3c, 0x0?, 0x0, 0x4157f0?, 0x1)
	/usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc00008de08 sp=0xc00008dce8 pc=0x458205
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).scanAndProcessFiles(0xc000162d90)
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:159 +0x3e5 fp=0xc00008dfc8 sp=0xc00008de08 pc=0x1862f85
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).Start.gowrap1()
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:105 +0x25 fp=0xc00008dfe0 sp=0xc00008dfc8 pc=0x1862b05
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008dfe8 sp=0xc00008dfe0 pc=0x47e2a1
created by github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).Start in goroutine 1
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:105 +0x65

goroutine 10 gp=0xc0009b4540 m=nil [runnable]:
runtime.asyncPreempt2()
	/usr/local/go/src/runtime/preempt.go:307 +0x39 fp=0xc00008c968 sp=0xc00008c948 pc=0x444ad9
runtime.asyncPreempt()
	/usr/local/go/src/runtime/preempt_amd64.s:53 +0xdb fp=0xc00008caf0 sp=0xc00008c968 pc=0x47f81b
github.com/pierrec/lz4/v4/internal/lz4block.(*Compressor).CompressBlock(0x3eb77c0?, {0xc005800000, 0x0?, 0xc0000a9ee0?}, {0xc005000000, 0x400000, 0x400000})
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:240 +0xb10 fp=0xc00008cbb8 sp=0xc00008caf0 pc=0x945670
github.com/pierrec/lz4/v4/internal/lz4block.CompressBlock({0xc005800000, 0x400000, 0x400000}, {0xc005000000, 0x400000, 0x400000})
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:100 +0x85 fp=0xc00008cc20 sp=0xc00008cbb8 pc=0x944ac5
github.com/pierrec/lz4/v4/internal/lz4stream.(*FrameDataBlock).Compress(0xc000162230, 0xc00071b5f0, {0xc005800000, 0xc00008cce0?, 0x400000}, 0x133e0?)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/pierrec/lz4/v4/internal/lz4stream/block.go:234 +0x7e fp=0xc00008cc80 sp=0xc00008cc20 pc=0x9487be
github.com/pierrec/lz4/v4.(*Writer).write(0xc00071b680, {0xc005800000?, 0xc005800000?, 0x400000?}, 0x0?)
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/pierrec/lz4/v4/writer.go:126 +0x16b fp=0xc00008ccf0 sp=0xc00008cc80 pc=0x94ceeb
github.com/pierrec/lz4/v4.(*Writer).ReadFrom(0xc00071b680, {0x25dfa80, 0xc0000133e0})
	/root/go/src/github.com/wal-g/wal-g/vendor/github.com/pierrec/lz4/v4/writer.go:230 +0x3af fp=0xc00008cde8 sp=0xc00008ccf0 pc=0x94d7cf
io.copyBuffer({0x7fcbe82b8578, 0xc00071b680}, {0x25dfa80, 0xc0000133e0}, {0xc003c00000, 0x1400000, 0x1400000})
	/usr/local/go/src/io/io.go:415 +0x151 fp=0xc00008ce60 sp=0xc00008cde8 pc=0x4c8871
io.CopyBuffer({0x7fcbe82b8578?, 0xc00071b680?}, {0x25dfa80?, 0xc0000133e0?}, {0xc003c00000?, 0x7fcbe82b8578?, 0x0?})
	/usr/local/go/src/io/io.go:402 +0x36 fp=0xc00008cea8 sp=0xc00008ce60 pc=0x4c8696
github.com/wal-g/wal-g/utility.FastCopy({0x7fcbe82b8578, 0xc00071b680}, {0x25dfa80, 0xc0000133e0})
	/root/go/src/github.com/wal-g/wal-g/utility/utility.go:209 +0x145 fp=0xc00008cf58 sp=0xc00008cea8 pc=0x8be7a5
github.com/wal-g/wal-g/internal.CompressAndEncrypt.func1()
	/root/go/src/github.com/wal-g/wal-g/internal/compress_and_encrypt.go:52 +0x75 fp=0xc00008cfe0 sp=0xc00008cf58 pc=0x170a6d5
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008cfe8 sp=0xc00008cfe0 pc=0x47e2a1
created by github.com/wal-g/wal-g/internal.CompressAndEncrypt in goroutine 1
	/root/go/src/github.com/wal-g/wal-g/internal/compress_and_encrypt.go:51 +0x22d

goroutine 27 gp=0xc000829180 m=nil [chan receive]:
runtime.gopark(0xc00008bf00?, 0x1852831?, 0x40?, 0x84?, 0xc000028440?)
	/usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00008bec8 sp=0xc00008bea8 pc=0x4463ce
runtime.chanrecv(0xc000056180, 0xc00008bf98, 0x1)
	/usr/local/go/src/runtime/chan.go:583 +0x3bf fp=0xc00008bf40 sp=0xc00008bec8 pc=0x40fd1f
runtime.chanrecv2(0x1bd5fa0?, 0xc0002c24e0?)
	/usr/local/go/src/runtime/chan.go:447 +0x12 fp=0xc00008bf68 sp=0xc00008bf40 pc=0x40f952
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).processFiles(0xc000162d90, 0xc000056180)
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:177 +0x45 fp=0xc00008bfc0 sp=0xc00008bf68 pc=0x1863325
github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).scanAndProcessFiles.gowrap2()
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:121 +0x25 fp=0xc00008bfe0 sp=0xc00008bfc0 pc=0x1863245
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008bfe8 sp=0xc00008bfe0 pc=0x47e2a1
created by github.com/wal-g/wal-g/internal/databases/postgres.(*BgUploader).scanAndProcessFiles in goroutine 9
	/root/go/src/github.com/wal-g/wal-g/internal/databases/postgres/bguploader.go:121 +0xd3

rax    0xca
rbx    0x0
rcx    0x4800a3
rdx    0x0
rdi    0x40ebb60
rsi    0x80
rbp    0x7ffef8184098
rsp    0x7ffef8184050
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x4
r13    0x1
r14    0x40eae20
r15    0x1
rip    0x4800a1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by x4m** [comment]
ugh... I do not understand what sends SIGQUIT to wal-g. Is it archive command execution?
Can you plz share your archive_command?

**Comment by holubnychyi** [comment]
It was a corrupted backup. Tried again with a different base backup, restored successfully. Thank you!

**Comment by x4m** [comment]
How come you had corrupted backup?

**Comment by holubnychyi** [comment]
It was a test, I made a few backups with different options. Looks like after base backup is done, I tried to recover with wrong time, another case when GCS_NORMALIZE_PREFIX has to be set to true after restore. Doesn't matter, if I do properly, it works fine. Thank you.
