### ISSUE TITLE
wal-g fail with WALG_UPLOAD_DISK_CONCURRENCY > 1 on Postgres with zstd

### ISSUE THREAD

**Issue by SoulKyu** [wal-g/wal-g#1839]
### Database name
PostgreSQL

# Issue description
When i activate 

### Describe your problem
WALG_UPLOAD_DISK_CONCURRENCY with a value > to 1 i have goroutine issue.

### Please provide steps to reproduce
Just start a wal-g backup with configuration provided below
`wal-g backup-push "$DATA_DIR"`
For more information, i'm using minio as s3 backend.

My Postgres instance is about 250GB

### Please add config and wal-g stdout/stderr logs for debug purpose
```yaml
  WALG_S3_PREFIX: "s3://{{ walg_env_backup_bucket.bucket_name }}/{{ postgresql_version_override }}/"
  WALG_USE_DATABASE_COMPOSER: "true"
  AWS_S3_FORCE_PATH_STYLE: "true"
  WALG_UPLOAD_CONCURRENCY: 32
  WALG_UPLOAD_DISK_CONCURRENCY: 4
  WALG_DOWNLOAD_CONCURRENCY: 16
  WALG_LOG_LEVEL: "NORMAL"
  WALG_TAR_SIZE_THRESHOLD: 4294967296
  WALG_S3_MAX_PART_SIZE: 5242880
  WALG_COMPRESSION_METHOD: zstd
  WALG_DECOMPRESSOR: "lz4,zstd"
  WALG_DELTA_MAX_STEPS: 5
  WALG_DELTA_ORIGIN: LATEST_FULL
  WALG_PREVENT_WAL_OVERWRITE: true
  ```
also you can use WALG_LOG_LEVEL=DEVEL for logs collecting

<details><summary>If you can, provide logs</summary>
<p>

```bash

2024-11-20 16:07:29 - [INFO] Initiating full backup
INFO: 2024/11/20 16:07:29.966127 Backup will be pushed to storage: default
INFO: 2024/11/20 16:07:30.000559 Calling pg_start_backup()
INFO: 2024/11/20 16:07:30.002205 Initializing the PG alive checker (interval=1m0s)...
INFO: 2024/11/20 16:07:30.002227 Starting a new tar bundle
INFO: 2024/11/20 16:07:30.002239 Walking ...
INFO: 2024/11/20 16:07:30.002447 Starting part 1 ...
INFO: 2024/11/20 16:07:30.004335 Starting part 2 ...
INFO: 2024/11/20 16:07:30.005188 Starting part 3 ...
INFO: 2024/11/20 16:07:30.007727 Starting part 4 ...
INFO: 2024/11/20 16:07:30.386589 Packing ...
INFO: 2024/11/20 16:07:30.412698 Finished writing part 1.
INFO: 2024/11/20 16:07:30.413991 Starting part 5 ...
fatal error: concurrent map writes

goroutine 183 [running]:
github.com/wal-g/wal-g/internal.(*RegularTarFileSets).AddFile(0xc000f8a270?, {0xc0043ea020?, 0x25df9d0?}, {0xc002ff7290, 0x16})
	/home/runner/work/wal-g/wal-g/internal/tar_file_sets.go:16 +0x45
github.com/wal-g/wal-g/internal/databases/postgres.DirDatabaseTarBallComposer.addListToTar({{0x25dcda0, 0xc00017e7a0}, 0xc000f86ba0, 0xc000f8a270, {0x25d9680, 0xc000278038}, {0x0, 0x0}, 0xc000f8a2a0}, {0xc003046000, ...})
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/dir_database_tar_ball_composer.go:122 +0x13c
github.com/wal-g/wal-g/internal/databases/postgres.DirDatabaseTarBallComposer.FinishComposing.func1()
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/dir_database_tar_ball_composer.go:103 +0x6a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/work/wal-g/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:78 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/work/wal-g/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0xa5
goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x18?)
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/sema.go:62 +0x27
sync.(*WaitGroup).Wait(0xc000f8a2a0?)
	/opt/hostedtoolcache/go/1.20.14/x64/src/sync/waitgroup.go:116 +0x4b
golang.org/x/sync/errgroup.(*Group).Wait(0xc00059c840)
	/home/runner/work/wal-g/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:56 +0x27
github.com/wal-g/wal-g/internal/databases/postgres.DirDatabaseTarBallComposer.FinishComposing({{0x25dcda0, 0xc00017e7a0}, 0xc000f86ba0, 0xc000f8a270, {0x25d9680, 0xc000278038}, {0x0, 0x0}, 0xc000f8a2a0})
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/dir_database_tar_ball_composer.go:107 +0x256
github.com/wal-g/wal-g/internal/databases/postgres.(*Bundle).FinishTarComposer(...)
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/bundle.go:426
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).uploadBackup(0xc0004f54a0)
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:333 +0x442
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).createAndPushBackup(0xc0004f54a0, {0x25db248, 0xc0000540c8})
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:178 +0x3ff
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).handleBackupPushLocal(0xc0004f54a0, {0x25db248, 0xc0000540c8})
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:427 +0x42c
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).HandleBackupPush(0xc0004f54a0, {0x25db248, 0xc0000540c8})
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:381 +0x8a
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x3c1b740, {0xc000f7b7b0, 0x1, 0x1?})
	/home/runner/work/wal-g/wal-g/cmd/pg/backup_push.go:117 +0xbe8
github.com/spf13/cobra.(*Command).execute(0x3c1b740, {0xc000f7b790, 0x1, 0x1})
	/home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x3c1b9c0)
	/home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/runner/work/wal-g/wal-g/cmd/pg/pg.go:55 +0x25
main.main()
	/home/runner/work/wal-g/wal-g/main/pg/main.go:8 +0x17
goroutine 110 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00041f000)
	/home/runner/work/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
	/home/runner/work/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:34 +0x96

goroutine 113 [syscall]:
os/signal.signal_recv()
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/sigqueue.go:152 +0x2f
os/signal.loop()
	/opt/hostedtoolcache/go/1.20.14/x64/src/os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
	/opt/hostedtoolcache/go/1.20.14/x64/src/os/signal/signal.go:151 +0x2a

goroutine 90 [chan receive]:
github.com/wal-g/wal-g/internal/databases/postgres.addSignalListener.func1()
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:660 +0x35
created by github.com/wal-g/wal-g/internal/databases/postgres.addSignalListener
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:659 +0xfc

goroutine 91 [chan receive]:
github.com/wal-g/wal-g/internal/databases/postgres.watchPgStatus(0x0?, 0xc00019c4b0)
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/pg_alive_watcher.go:27 +0x33
github.com/wal-g/wal-g/internal/databases/postgres.NewPgWatcher.func1()
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/pg_alive_watcher.go:14 +0x2a
created by github.com/wal-g/wal-g/internal/databases/postgres.NewPgWatcher
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/pg_alive_watcher.go:13 +0xab

goroutine 92 [chan receive]:
github.com/wal-g/wal-g/internal/databases/postgres.addPgIsAliveChecker.func1()
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:675 +0x38
created by github.com/wal-g/wal-g/internal/databases/postgres.addPgIsAliveChecker
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:674 +0x1aa

goroutine 93 [chan receive]:
github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).initBackupTerminator.func1()
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:648 +0x35
created by github.com/wal-g/wal-g/internal/databases/postgres.(*BackupHandler).initBackupTerminator
	/home/runner/work/wal-g/wal-g/internal/databases/postgres/backup_push_handler.go:647 +0x159

goroutine 94 [select]:
net/http.(*Transport).getConn(0x3c0ad60, 0xc00674dc40, {{}, 0x0, {0xc000f1db6d, 0x5}, {0xc000576030, 0x18}, 0x0})
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/transport.go:1382 +0x5c6
net/http.(*Transport).roundTrip(0x3c0ad60, 0xc0001bfd00)
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/transport.go:590 +0x79e
net/http.(*Transport).RoundTrip(0x0?, 0xc0067101a0?)
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/roundtrip.go:17 +0x19
github.com/wal-g/wal-g/pkg/storages/s3.(*loggingTransport).RoundTrip(0x486606859f934e0b?, 0xc0001bfd00)
	/home/runner/work/wal-g/wal-g/pkg/storages/s3/transport_with_logging.go:15 +0x3b
net/http.send(0xc0001bfd00, {0x25acb60, 0xc00107ddd0}, {0x8?, 0x218b100?, 0x0?})
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/client.go:252 +0x5f7
net/http.(*Client).send(0x3e3dba0, 0xc0001bfd00, {0x2202e07?, 0x2?, 0x0?})
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0x3e3dba0, 0xc0001bfd00)
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/client.go:716 +0x8fb
net/http.(*Client).Do(...)
	/opt/hostedtoolcache/go/1.20.14/x64/src/net/http/client.go:582
github.com/aws/aws-sdk-go/aws/corehandlers.sendFollowRedirects(0xc1c7a07b98ac8371?)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:120 +0x27
github.com/aws/aws-sdk-go/aws/corehandlers.glob..func3(0xc000ea4000)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:112 +0x1a6
github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc000ea4228, 0xc000ea4000)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:267 +0x9c
github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest(0xc000ea4000)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:602 +0xbf
github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc000ea4000)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:555 +0x156
github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).singlePart(0xc0005227e0, {0x25d2f40?, 0xc000f8a180}, 0x413707?)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:537 +0x27a
github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).upload(0xc0005227e0)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:390 +0x4b9
github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.UploadWithContext({0x500000, 0x10, 0x0, 0x2710, {0x26009c0, 0xc000014870}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
	/home/runner/work/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:305 +0x1f0
github.com/wal-g/wal-g/pkg/storages/s3.(*Uploader).upload(0xc000f6ca10, {0x25db248, 0xc0000540c8}, {0xc000f1dfc4, 0x10}, {0xc000f03040, 0x50}, {0x25acba0?, 0xc001122ff0?})
	/home/runner/work/wal-g/wal-g/pkg/storages/s3/uploader.go:106 +0xa5
github.com/wal-g/wal-g/pkg/storages/s3.(*Folder).PutObjectWithContext(0x0?, {0x25db248, 0xc0000540c8}, {0xc000f96240?, 0x0?}, {0x25acba0, 0xc001122ff0})
	/home/runner/work/wal-g/wal-g/pkg/storages/s3/folder.go:71 +0xa7
github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectToFirst(...)
	/home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:450
github.com/wal-g/wal-g/internal/multistorage.Folder.PutObjectWithContext({{0x25dcfe0, 0xc000780ed0}, 0xc00103e870, {0xc000790860, 0x1, 0x1}, {0xc000055050, 0x10}, {0x0, 0x0, ...}}, ...)
	/home/runner/work/wal-g/wal-g/internal/multistorage/folder.go:433 +0xe5
github.com/wal-g/wal-g/internal.(*RegularUploader).Upload(0xc000f8c5c0, {0x25db248, 0xc0000540c8}, {0xc000f96240, 0x3d}, {0x25cd9a0, 0xc000278058})
	/home/runner/work/wal-g/wal-g/internal/uploader.go:178 +0x1ab
github.com/wal-g/wal-g/internal.(*StorageTarBall).startUpload.func1()
	/home/runner/work/wal-g/wal-g/internal/storage_tar_ball.go:87 +0x6d
created by github.com/wal-g/wal-g/internal.(*StorageTarBall).startUpload
	/home/runner/work/wal-g/wal-g/internal/storage_tar_ball.go:86 +0x2cc
goroutine 278 [runnable]:
github.com/klauspost/compress/zstd.(*Encoder).nextBlock.func2()
	/home/runner/work/wal-g/wal-g/vendor/github.com/klauspost/compress/zstd/encoder.go:307
runtime.goexit()
	/opt/hostedtoolcache/go/1.20.14/x64/src/runtime/asm_amd64.s:1598 +0x1
created by github.com/klauspost/compress/zstd.(*Encoder).nextBlock
	/home/runner/work/wal-g/wal-g/vendor/github.com/klauspost/compress/zstd/encoder.go:307 +0x6aa

goroutine 370 [runnable]:
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/work/wal-g/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:75
created by golang.org/x/sync/errgroup.(*Group).Go
	/home/runner/work/wal-g/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:75 +0xa5
```
</p>
</details>

**Comment by SoulKyu** [comment]
For information, logs has been truncated because they were to huge.

**Comment by ostinru** [comment]
> For information, logs has been truncated because they were to huge.

Thats enough to find an issue.

**Comment by SoulKyu** [comment]
If i can provide some extra information : 

It doesn't look to fail when using DELTA backup but it seems that delta backup is not really using `WALG_UPLOAD_DISK_CONCURRENCY` at all and just ignore this parameter.

**Comment by x4m** [comment]
btw I think zstd is disabled. It was corrupting data in 2018, they fixed a bug in 2021, but we still did not turn it on back :)
you do not need to specify decompressor in config, WAL-G have to determine it on it's own.

**Comment by x4m** [comment]
And thanks for fixing bug, of course!

**Comment by SoulKyu** [comment]
> btw I think zstd is disabled. It was corrupting data in 2018, they fixed a bug in 2021, but we still did not turn it on back :) you do not need to specify decompressor in config, WAL-G have to determine it on it's own.

It look like it has been turned it on, so, i don't understand why this shouldn't be activated if the bug is from 2018 and has been correct 3years ago ?
What did you exactly mean by "is disabled" ?

**Comment by x4m** [comment]
I just had a stale cache
https://github.com/wal-g/wal-g/pull/1326

**Comment by SoulKyu** [comment]
@x4m Ok ! 

Did you think the fix will be in next release ? 
And did you have any idea on when the release will be available ?

**Comment by x4m** [comment]
I think we will have a release with support for CloudberryDB in December. This release will contain your code.

**Comment by ostinru** [comment]
> Did you think the fix will be in next release ? And did you have any idea on when the release will be available ?

It will be in 3.0.5. I am going to release it in few next days.
