### ISSUE TITLE
Segfault when using delete retain

### ISSUE THREAD

**Issue by MaxwellDAssistek** [wal-g/wal-g#1863]
### Database name
PostgreSQL 16

# Issue description

### Describe your problem
When attempting to use the delete retain command I get a segfault.

### Please provide steps to reproduce
`/backup_share/wal-g --config /backup_share/config.json delete retain 5 --after 2024-11-29T19:12:15`

### Please add config and wal-g stdout/stderr logs for debug purpose

Wal-g is being run in a container based on the `ubuntu:latest` base image.

<details><summary>Logs</summary>

```bash
+ /backup_share/wal-g --config /backup_share/config.json delete retain 5 --after 2024-11-29T19:12:15
DEBUG: 2024/12/13 19:12:15.881230 --- COMPILED ENVIRONMENT VARS ---
        AZURE_STORAGE_ACCESS_KEY=--HIDDEN--
        AZURE_STORAGE_ACCOUNT=backup
        PGBACKREST_STANZA=main
        PGHOST=127.0.0.1
        PGPASSWORD=--HIDDEN--
        PGUSER=postgres
        TOTAL_BG_UPLOADED_LIMIT=32
        WALG_ALIVE_CHECK_INTERVAL=1m
        WALG_AZ_PREFIX=azure://backups/Dev
        WALG_COMPRESSION_METHOD=zstd
        WALG_DAEMON_WAL_UPLOAD_TIMEOUT=60s
        WALG_DELTA_MAX_STEPS=0
        WALG_DOWNLOAD_CONCURRENCY=10
        WALG_DOWNLOAD_FILE_RETRIES=15
        WALG_ENVELOPE_CACHE_EXPIRATION=0
        WALG_FAILOVER_STORAGES_CACHE_LIFETIME=15m
        WALG_FAILOVER_STORAGES_CHECK_SIZE=1mb
        WALG_FAILOVER_STORAGES_CHECK_TIMEOUT=30s
        WALG_INTEGRITY_MAX_DELAYED_WALS=0
        WALG_LIBSODIUM_KEY_TRANSFORM=none
        WALG_LOG_LEVEL=DEVEL
        WALG_PG_WAL_SIZE=16
        WALG_PREVENT_WAL_OVERWRITE=false
        WALG_SERIALIZER_TYPE=json_default
        WALG_SKIP_REDUNDANT_TARS=false
        WALG_STORE_ALL_CORRUPT_BLOCKS=false
        WALG_TAR_DISABLE_FSYNC=false
        WALG_TAR_SIZE_THRESHOLD=1073741823
        WALG_UPLOAD_CONCURRENCY=16
        WALG_UPLOAD_DISK_CONCURRENCY=1
        WALG_UPLOAD_QUEUE=2
        WALG_UPLOAD_WAL_METADATA=NOMETADATA
        WALG_USE_COPY_COMPOSER=false
        WALG_USE_DATABASE_COMPOSER=false
        WALG_USE_RATING_COMPOSER=false
        WALG_USE_REVERSE_UNPACK=false
        WALG_USE_WAL_DELTA=false
        WALG_VERIFY_PAGE_CHECKSUMS=false
        WALG_WITHOUT_FILES_METADATA=false
INFO: 2024/12/13 19:12:15.881645 Backup to delete will be searched in storages: [default]
INFO: 2024/12/13 19:12:15.881739 retrieving permanent objects
DEBUG: 2024/12/13 19:12:16.187456 processing base_00000001000000000000004A_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187473 processing base_000000010000000000000048_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187475 processing base_000000010000000000000046_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187477 processing base_000000010000000000000044_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187478 processing base_000000010000000000000042_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187734 processing base_000000010000000000000011_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187741 processing base_000000010000000000000014_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187743 processing base_000000010000000000000016_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187744 processing base_000000010000000000000024_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187746 processing base_000000010000000000000026_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187747 processing base_000000010000000000000028_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187749 processing base_00000001000000000000002A_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187750 processing base_00000001000000000000002C_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187752 processing base_000000010000000000000036_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187753 processing base_000000010000000000000038_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187754 processing base_00000001000000000000003A_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187756 processing base_00000001000000000000003C_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187758 processing base_00000001000000000000003E_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187760 processing base_000000010000000000000040_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187761 processing base_000000010000000000000042_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187763 processing base_000000010000000000000044_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187764 processing base_000000010000000000000046_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187766 processing base_000000010000000000000048_backup_stop_sentinel.json
DEBUG: 2024/12/13 19:12:16.187768 processing base_00000001000000000000004A_backup_stop_sentinel.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1876aa6]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal/databases/postgres.timelineAndSegmentNoLess({0x77df70246718?, 0xc000492310?}, {0x0, 0x0})
        /home/runner/work/wal-g/wal-g/internal/databases/postgres/delete.go:204 +0x46
github.com/wal-g/wal-g/internal.NewDeleteHandler.func1({0x0?, 0x0?}, {0x77df70246718?, 0xc000492310?})
        /home/runner/work/wal-g/wal-g/internal/delete_handler.go:91 +0x3d
github.com/wal-g/wal-g/internal.(*DeleteHandler).FindTargetRetainAfterName(0xc00082bd80, 0x5, {0x7ffe6e7506f3, 0x13}, 0x0)
        /home/runner/work/wal-g/wal-g/internal/delete_handler.go:302 +0x42b
github.com/wal-g/wal-g/internal.(*DeleteHandler).FindTargetRetainAfter(0xc00082bd80, 0x5, {0x7ffe6e7506f3, 0x13}, 0x0)
        /home/runner/work/wal-g/wal-g/internal/delete_handler.go:274 +0x5b
github.com/wal-g/wal-g/internal.(*DeleteHandler).HandleDeleteRetainAfter(0xc00082bd80, {0xc0006c4960?, 0xc000de2b10?, 0xc000de2b40?}, 0x0)
        /home/runner/work/wal-g/wal-g/internal/delete_handler.go:148 +0x20c
github.com/wal-g/wal-g/cmd/pg.runDeleteRetain(0x3cd9d20, {0xc0006c4960, 0x1, 0x5})
        /home/runner/work/wal-g/wal-g/cmd/pg/delete.go:91 +0x1d4
github.com/spf13/cobra.(*Command).execute(0x3cd9d20, {0xc0006c4910, 0x5, 0x5})
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:860 +0x684
github.com/spf13/cobra.(*Command).ExecuteC(0x3cdaea0)
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:974 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/work/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:902
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/runner/work/wal-g/wal-g/cmd/pg/pg.go:55 +0x1f
main.main()
        /home/runner/work/wal-g/wal-g/main/pg/main.go:8 +0xf
```

</p>
</details>

**Comment by ostinru** [comment]
Previous fix: https://github.com/wal-g/wal-g/pull/818
