### ISSUE TITLE
Segfault on backup push

### ISSUE THREAD

**Issue by qwertys-ru** [wal-g/wal-g#227]
Trying to push backup of database to S3. WAL-G always crashes on pushing:

```
+ wal-g backup-push /var/lib/postgresql/data
Path:  minikube/
INFO: 2019/03/31 21:52:16.089638 Doing full backup.
INFO: 2019/03/31 21:52:16.319483 Walking ...
INFO: 2019/03/31 21:52:16.319752 Starting part 1 ...
INFO: 2019/03/31 21:52:16.327558 Finished writing part 1.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10c97fb]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc0002c8240, 0x1409803, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:352 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0x7ffe7f20caba, 0x18, 0xc000339a00)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:142 +0x617
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/wal-g/main.go:148 +0x72d
```

Using wal-g 0.2.7 inside minikube.

Please let me know if I have to provide any other information.

**Comment by x4m** [comment]
Hi! 
Thanks for report!
Essentially this is #120
