### ISSUE TITLE
Properties not working from config file

### ISSUE THREAD

**Issue by Tri0L** [wal-g/wal-g#274]
```
$ whoami
postgres

$ ls -la
-rw-rw-r--  1 postgres postgres  329 May 13 15:14 .walg.json

$ cat ./.walg.json 
{
	"WALG_LOG_LEVEL": "DEVEL",
	"USER": "postgres",
	"PGPORT": "5432",
	"PGUSER": "postgres",
	"OS_PASSWORD": "password",
	"PGHOST": "/var/run/postgresql",
	"OS_AUTH_URL": "authurl",
	"OS_USERNAME": "user",
	"OS_TENANT_NAME": "user",
	"WALG_SWIFT_PREFIX": "swift://wal-g/somefolder",
	"WALG_DELTA_MAX_STEPS": "5"
}
```

Time to time different errors:
```
$ wal-g backup-list
ERROR: 2019/05/13 16:17:03.799099 Settings OS_PASSWORD is unknown
panic: Settings OS_PASSWORD is unknown

goroutine 1 [running]:
log.(*Logger).Panic(0xc0000fe0f0, 0xc0002a3cd0, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.11.9.linux.amd64/src/log/log.go:212 +0xbe
github.com/wal-g/wal-g/internal.verifyConfig()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:62 +0x2f7
github.com/wal-g/wal-g/internal.init.1()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:48 +0x21d


$ wal-g backup-list
ERROR: 2019/05/13 16:17:14.140655 Settings OS_AUTH_URL is unknown
panic: Settings PGUSER is unknown

goroutine 1 [running]:
log.(*Logger).Panic(0xc0000fe0f0, 0xc0002a3cd0, 0x1, 0x1)
        /home/travis/.gimme/versions/go1.11.9.linux.amd64/src/log/log.go:212 +0xbe
github.com/wal-g/wal-g/internal.verifyConfig()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:62 +0x2f7
github.com/wal-g/wal-g/internal.init.1()
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/config.go:48 +0x21d

```

**Comment by g0djan** [comment]
@Tri0L We fixed reading settings from config some time ago(It's possible with --config=...) 
Reopen issue if you still can reproduce it.
