### ISSUE TITLE
backup-push: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ZoorGan** [wal-g/wal-g#402]
Hello.
I'm trying to run the command ```wal-g backup-push 123```

Version: v0.2.12 (pre-release)

```
INFO: 2019/09/05 19:29:18.140512 Doing full backup.
WARNING: 2019/09/05 19:29:18.192599 It seems your archive_command is not configured. This will cause inconsistent backup. Please consider configuring WAL archiving.
INFO: 2019/09/05 19:29:18.193208 Calling pg_start_backup()
INFO: 2019/09/05 19:29:18.345595 Walking ...
WARNING: 2019/09/05 19:29:18.345644 123  deleted during filepath walk
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bb3eb]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc0001d5970, 0x164df6e, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:364 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000c1770, 0x7ffc7c6c4777, 0x3, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:135 +0x651
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x227c960, 0xc0002f7c30, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x227c960, 0xc0002f7c10, 0x1, 0x1, 0x227c960, 0xc0002f7c10)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x227d2e0, 0x1, 0x227c240, 0xc0002e9f78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x227d2e0, 0x914c70, 0xc000080058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

**Comment by x4m** [comment]
Hi! Seems like you are making backup not from PGDATA, like in #120

Eventually, we will fix it. PR is welcome.

**Comment by Dmitri191** [comment]
Hello!
I had same error after start backup-push:
wal-g --config /var/lib/pgsql/walg/wal-gs3.json backup-push <datadir>

```
# ./wal-g --version
wal-g version v0.2.13	271f64f	2019.10.15_19:01:18	PostgreSQL
```

```
May 07 01:00:01 INFO: 2020/05/07 01:00:01.684336 Using config file: /var/lib/pgsql/walg/wal-gs3.json
May 07 01:00:05 INFO: 2020/05/07 01:00:05.460211 Delta will be made from full backup.
May 07 01:00:05 panic: runtime error: invalid memory address or nil pointer dereference
May 07 01:00:05 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bb114]
May 07 01:00:05
May 07 01:00:05 goroutine 1 [running]:
May 07 01:00:05 github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000a36e0, 0xc0000dcdb0, 0x27, 0x0)
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:108 +0x16e4
May 07 01:00:05 github.com/wal-g/wal-g/cmd/pg.glob..func4(0x2288c00, 0xc000279ad0, 0x1, 0x3)
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
May 07 01:00:05 github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x2288c00, 0xc000366100, 0x3, 0x4, 0x2288c00, 0xc000366100)
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
May 07 01:00:05 github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x22897e0, 0x1, 0x22884e0, 0xc000309f78)
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
May 07 01:00:05 github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x22897e0, 0x916cc0, 0xc000080058)
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
May 07 01:00:05 github.com/wal-g/wal-g/cmd/pg.Execute()
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
May 07 01:00:05 main.main()
May 07 01:00:05         /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

PostgreSQL have not errors in logfile.
After repeat backup-push command, wal-g was complete correct.
