### ISSUE TITLE
WALG_DELTA_ORIGIN=LATEST_FULL: backup-push: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kruftik** [wal-g/wal-g#406]
wal-g  v0.2.9, v0.2.11

WALG_DELTA_MAX_STEPS > 0
**WALG_DELTA_ORIGIN=LATEST_FULL**

wal-g crashes on backup-push command with the following trace if full backup already exists in the store (FS):
```
root@docker-desktop:/# wal-g backup-push /stolon/postgres
INFO: 2019/09/13 09:55:24.925602 Couldn't find previous backup. Doing full backup.
INFO: 2019/09/13 09:55:24.957429 Calling pg_start_backup()
INFO: 2019/09/13 09:55:25.459135 Walking ...
INFO: 2019/09/13 09:55:25.461665 Starting part 1 ...
INFO: 2019/09/13 09:55:28.118767 Finished writing part 1.
INFO: 2019/09/13 09:55:28.119452 Starting part 2 ...
INFO: 2019/09/13 09:55:28.125116 /global/pg_control
INFO: 2019/09/13 09:55:28.128533 Finished writing part 2.
INFO: 2019/09/13 09:55:28.129525 Calling pg_stop_backup()
INFO: 2019/09/13 09:55:29.486455 Starting part 3 ...
INFO: 2019/09/13 09:55:29.495286 backup_label
INFO: 2019/09/13 09:55:29.497083 tablespace_map
INFO: 2019/09/13 09:55:29.497970 Finished writing part 3.
INFO: 2019/09/13 09:55:29.505148 Wrote backup with name base_00000001000000000000001B

root@docker-desktop:/# wal-g backup-push /stolon/postgres
INFO: 2019/09/13 09:55:31.159653 Delta will be made from full backup.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x124b461]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000df810, 0xc00032c000, 0x10, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:85 +0x16f1
github.com/wal-g/wal-g/cmd/pg.glob..func3(0x219d160, 0xc000179b90, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:29 +0x71
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x219d160, 0xc000179b70, 0x1, 0x1, 0x219d160, 0xc000179b70)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x219dae0, 0x1, 0x219cca0, 0xc0002edf78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x219dae0, 0x8f54b0, 0xc000086058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

When default WALG_DELTA_ORIGIN=LATEST is used, problem does not appear:

```
root@docker-desktop:/# export WALG_DELTA_ORIGIN=LATEST
root@docker-desktop:/# wal-g backup-push /stolon/postgres
INFO: 2019/09/13 09:57:13.549581 Delta backup from base_00000001000000000000001B with LSN 1b000028.
INFO: 2019/09/13 09:57:13.586479 Calling pg_start_backup()
INFO: 2019/09/13 09:57:14.056106 Walking ...
INFO: 2019/09/13 09:57:14.059707 Starting part 1 ...
INFO: 2019/09/13 09:57:14.589325 Finished writing part 1.
INFO: 2019/09/13 09:57:14.590382 Starting part 2 ...
INFO: 2019/09/13 09:57:14.593320 /global/pg_control
INFO: 2019/09/13 09:57:14.596623 Finished writing part 2.
INFO: 2019/09/13 09:57:14.597734 Calling pg_stop_backup()
INFO: 2019/09/13 09:57:16.115866 Starting part 3 ...
INFO: 2019/09/13 09:57:16.142124 backup_label
INFO: 2019/09/13 09:57:16.142568 tablespace_map
INFO: 2019/09/13 09:57:16.143413 Finished writing part 3.
INFO: 2019/09/13 09:57:16.152686 Wrote backup with name base_00000001000000000000001D_D_00000001000000000000001B
```

As soon as 1st delta backup with WALG_DELTA_ORIGIN=LATEST has been saved, WALG_DELTA_ORIGIN=LATEST_FULL starts working as expected:

```
root@docker-desktop:/# export WALG_DELTA_ORIGIN=LATEST_FULL
root@docker-desktop:/# wal-g backup-push /stolon/postgres
INFO: 2019/09/13 10:00:09.468381 Delta will be made from full backup.
INFO: 2019/09/13 10:00:09.475378 Delta backup from base_00000001000000000000001B with LSN 1b000028.
INFO: 2019/09/13 10:00:09.512849 Calling pg_start_backup()
INFO: 2019/09/13 10:00:09.910139 Walking ...
INFO: 2019/09/13 10:00:09.913224 Starting part 1 ...
INFO: 2019/09/13 10:00:10.545878 Finished writing part 1.
INFO: 2019/09/13 10:00:10.546665 Starting part 2 ...
INFO: 2019/09/13 10:00:10.550410 /global/pg_control
INFO: 2019/09/13 10:00:10.555584 Finished writing part 2.
INFO: 2019/09/13 10:00:10.557689 Calling pg_stop_backup()
INFO: 2019/09/13 10:00:12.007882 Starting part 3 ...
INFO: 2019/09/13 10:00:12.032421 backup_label
INFO: 2019/09/13 10:00:12.032489 tablespace_map
INFO: 2019/09/13 10:00:12.033313 Finished writing part 3.
INFO: 2019/09/13 10:00:12.041876 Wrote backup with name base_00000001000000000000001F_D_00000001000000000000001B
```
```

**Comment by x4m** [comment]
Who, that's a bug...
Will you compose a PR to fix this?

**Comment by kruftik** [comment]
@x4m, have you seen the PR? is it under review now or just was missed ?

**Comment by x4m** [comment]
Hi! Yeah, sorry, I was a bit busy.. We will review asap.
