### ISSUE TITLE
wal-g backup-push hangs while pushing to Swift storage

### ISSUE THREAD

**Issue by skvav** [wal-g/wal-g#409]
Caught this problem second time. Again it happened right after pg_stop_backup() according to log.
backup-push runs on production server in archive mode with wal-g wal-push archive command. backup-push starts right after pg_repack finished its work. Maybe it is a cause of this freeze? When I run backup-push manually it usually works successfully.

```INFO: 2019/09/14 03:58:55.640727 Starting part 124 ...
INFO: 2019/09/14 03:58:55.742759 Finished writing part 124.
INFO: 2019/09/14 03:58:55.750918 Starting part 125 ...
INFO: 2019/09/14 03:58:55.750957 /global/pg_control
INFO: 2019/09/14 03:58:55.790923 Finished writing part 125.
INFO: 2019/09/14 03:58:55.804163 Calling pg_stop_backup()
SIGABRT: abort
PC=0x968d21 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x22c36c0, 0x80, 0x0, 0x0, 0x0, 0xc001ab2800, 0x0, 0x0, 0x7fff38a58200, 0x919c72, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x22c36c0, 0xc000000000, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x22c36c0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc000054f00, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000385380)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x13aa5d0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait, 161 minutes]:
internal/poll.runtime_pollWait(0x7f37fe505d60, 0x72, 0xc0004150a8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000328318, 0x72, 0xffffffffffffff00, 0x17dcd00, 0x2284d48)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000328318, 0xc00020e500, 0xad4, 0xad4)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000328300, 0xc00020e52c, 0xad4, 0xad4, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000328300, 0xc00020e52c, 0xad4, 0xad4, 0x7f37fe574310, 0x0, 0xc0004153b8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00020c008, 0xc00020e52c, 0xad4, 0xad4, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/net/net.go:177 +0x68
io.ReadAtLeast(0x7f37fe3e1020, 0xc00020c008, 0xc00020e52c, 0xad4, 0xad4, 0x5, 0xc1c, 0x148, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/io/io.go:310 +0x88
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader.(*ChunkReader).appendAtLeast(0xc00028e1c0, 0x5, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader/chunkreader.go:73 +0x7f
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader.(*ChunkReader).Next(0xc00028e1c0, 0x5, 0x1691548, 0x38812a8f, 0xc000415338, 0xc000415358, 0xe031df)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader/chunkreader.go:63 +0xf5
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/pgproto3.(*Frontend).Receive(0xc000065880, 0x10d5b04aba01, 0x22c2640, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/pgproto3/frontend.go:55 +0x3c5
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Conn).rxMsg(0xc000326000, 0x17e9560, 0xc000065a58, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/conn.go:1413 +0x52
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Rows).Next(0xc000212470, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/query.go:126 +0x2b9
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Row).Scan(0xc000212470, 0xc000415528, 0x3, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/query.go:30 +0x40
github.com/wal-g/wal-g/internal.(*PgQueryRunner).StopBackup(0xc000cdf1d0, 0xc000cdf1d0, 0x0, 0x0, 0x3c, 0x1691548, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/queryRunner.go:146 +0x67a
github.com/wal-g/wal-g/internal.(*Bundle).UploadLabelFiles(0xc000324000, 0xc000326000, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:418 +0x6c
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0004b60f0, 0xc000483220, 0x1b, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:138 +0x6b0
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x227c960, 0xc00031bc30, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x227c960, 0xc00031bc10, 0x1, 0x1, 0x227c960, 0xc00031bc10)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x227d2e0, 0x1, 0x227c240, 0xc00030df78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x227d2e0, 0x914c70, 0xc0000a0058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 6 [select]:
github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0000e1400)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.init.0
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

rax    0xca
rbx    0x22c3580
rcx    0x968d23
rdx    0x0
rdi    0x22c36c0
rsi    0x80
rbp    0x7fff38a581c8
rsp    0x7fff38a58180
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x59
r13    0x12
r14    0x17cb475
r15    0x0
rip    0x968d21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0```

**Comment by g0djan** [comment]
Hi, which version do you use?

**Comment by skvav** [comment]
The latest pre-release, 0.2.12

**Comment by x4m** [comment]
Hi! Thanks for the report! Looks like WAL-G finished backup and is waiting for pg_stop_backup() to complete. Plz inspect PostgreSQL log, what is it waiting for?.

**Comment by skvav** [comment]
`2019-09-14 03:59:55 MSK [28996-1] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
2019-09-14 03:59:55 MSK [28996-2] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.`

This text repeats then in log with increasing delay, for example:

`2019-09-14 04:06:56 MSK [28996-7] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (480 seconds elapsed)
2019-09-14 04:06:56 MSK [28996-8] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.`

...

`2019-09-14 04:14:56 MSK [28996-9] postgres@postgres WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (960 seconds elapsed)
2019-09-14 04:14:56 MSK [28996-10] postgres@postgres HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.`

**Comment by x4m** [comment]
@skvav you need to find why did wal archive command fail. Look for messages with WAL file names like 000000010000000100000001.

**Comment by skvav** [comment]
Today it happened again, so I tried to investigate it more thoroughly.
There was a hanging backup-push process for archive base_00000001000014CE000000B5
It was accompanied by hanging `/usr/local/bin/wal-g wal-push pg_wal/00000001000014B600000094` process. After I waited ~10 minutes wal-push did not switch to next wal segment, so I killed it with kill -ABRT and got this stack trace in postgresql log:
```
SIGABRT: abort
PC=0x968d23 m=0 sigcode=0

goroutine 83 [syscall]:
runtime.notetsleepg(0x22c7040, 0x2faeca8, 0x1)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/lock_futex.go:227 +0x37 fp=0xc0000f7758 sp=0xc0000f7728 pc=0x919f47
runtime.timerproc(0x22c7020)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/time.go:288 +0x30e fp=0xc0000f77d8 sp=0xc0000f7758 pc=0x95803e
runtime.goexit()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0000f77e0 sp=0xc0000f77d8 pc=0x966ee1
created by runtime.(*timersBucket).addtimerLocked
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/time.go:170 +0x114

goroutine 1 [sleep]:
time.Sleep(0x2faf080)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/time.go:105 +0x14f
github.com/wal-g/wal-g/internal.(*BgUploader).Stop(0xc0000df090)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bguploader.go:70 +0x2c
github.com/wal-g/wal-g/internal.HandleWALPush(0xc0000def00, 0x7ffcf7f1fde1, 0x1f)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/wal_push_handler.go:52 +0x2be
github.com/wal-g/wal-g/cmd/pg.glob..func7(0x227c240, 0xc00031dc40, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/wal_push.go:19 +0x69
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x227c240, 0xc00031dc10, 0x1, 0x1, 0x227c240, 0xc00031dc10)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x227d2e0, 0x1, 0x227c240, 0xc00030df78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x227d2e0, 0x914c70, 0xc00009e058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 6 [select]:
github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0000df400)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.init.0
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

rax    0xfffffffffffffffc
rbx    0x2faeca8
rcx    0x968d23
rdx    0x0
rdi    0x22c7040
rsi    0x80
rbp    0xc0000f76e0
rsp    0xc0000f7698
r8     0x0
r9     0x0
r10    0xc0000f76d0
r11    0x202
r12    0x1
r13    0x1
r14    0x0
r15    0xc00003b1a0
rip    0x968d23
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
2019-09-17 11:37:31 MSK [6670-1] LOG:  archive command failed with exit code 2
2019-09-17 11:37:31 MSK [6670-2] DETAIL:  The failed archive command was: envdir /etc/wal-g.d/env /usr/local/bin/wal-g wal-push pg_wal/00000001000014B600000094
```

After that wal-push started to rotate wal segments, but backup-push did not come alive. I killed it and got log:
```
SIGABRT: abort
PC=0x968d21 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x22c36c0, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fffc9bb0e00, 0x919c72, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x22c36c0, 0x7fff00000000, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x22c36c0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc000049400, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000392180)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x13aa5d0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [IO wait, 212 minutes]:
internal/poll.runtime_pollWait(0x7ffaf9e50d60, 0x72, 0xc0002e10a8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc000538318, 0x72, 0xffffffffffffff00, 0x17dcd00, 0x2284d48)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc000538318, 0xc0005c0500, 0xad4, 0xad4)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc000538300, 0xc0005c052c, 0xad4, 0xad4, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc000538300, 0xc0005c052c, 0xad4, 0xad4, 0x7ffaf9eac000, 0x0, 0xc0002e13b8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00053a008, 0xc0005c052c, 0xad4, 0xad4, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/net/net.go:177 +0x68
io.ReadAtLeast(0x7ffaf409a020, 0xc00053a008, 0xc0005c052c, 0xad4, 0xad4, 0x5, 0xc1c, 0x148, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/io/io.go:310 +0x88
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader.(*ChunkReader).appendAtLeast(0xc000374380, 0x5, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader/chunkreader.go:73 +0x7f
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader.(*ChunkReader).Next(0xc000374380, 0x5, 0x1691548, 0x25eef104, 0xc0002e1338, 0xc0002e1358, 0xe031df)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/chunkreader/chunkreader.go:63 +0xf5
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/pgproto3.(*Frontend).Receive(0xc000065880, 0x112b609a4e01, 0x22c2640, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/pgproto3/frontend.go:55 +0x3c5
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Conn).rxMsg(0xc000536000, 0x17e9560, 0xc000065a58, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/conn.go:1413 +0x52
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Rows).Next(0xc000326470, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/query.go:126 +0x2b9
github.com/wal-g/wal-g/vendor/github.com/jackc/pgx.(*Row).Scan(0xc000326470, 0xc0002e1528, 0x3, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/jackc/pgx/query.go:30 +0x40
github.com/wal-g/wal-g/internal.(*PgQueryRunner).StopBackup(0xc0002e6f50, 0xc0002e6f50, 0x0, 0x0, 0x3c, 0x1691548, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/queryRunner.go:146 +0x67a
github.com/wal-g/wal-g/internal.(*Bundle).UploadLabelFiles(0xc000304000, 0xc000536000, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:418 +0x6c
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc00042a0f0, 0xc00046e980, 0x1b, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:138 +0x6b0
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x227c960, 0xc00031bc30, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x227c960, 0xc00031bc10, 0x1, 0x1, 0x227c960, 0xc00031bc10)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x227d2e0, 0x1, 0x227c240, 0xc00030bf78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x227d2e0, 0x914c70, 0xc0000a0058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 6 [select]:
github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0000e1400)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.init.0
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

rax    0xca
rbx    0x22c3580
rcx    0x968d23
rdx    0x0
rdi    0x22c36c0
rsi    0x80
rbp    0x7fffc9bb0dc8
rsp    0x7fffc9bb0d80
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x22c2640
r13    0x4
r14    0x3
r15    0x200
rip    0x968d21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```
