### ISSUE TITLE
Errors for  S3 access keys

### ISSUE THREAD

**Issue by x88** [wal-g/wal-g#412]
When using S3 keys, crash after uploading data 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bb3eb]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc0001e9970, 0x164df6e, 0x3, 0x0, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:364 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000d5860, 0xc00003ce10, 0x2e, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:135 +0x651
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x227c960, 0xc00030fc30, 0x1, 0x1)
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x227c960, 0xc00030fc10, 0x1, 0x1, 0x227c960, 0xc00030fc10)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x227d2e0, 0x1, 0x227c240, 0xc0002fdf78)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x227d2e0, 0x914c70, 0xc000094058)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

**Comment by x4m** [comment]
Hi! thanks for reporting
I think it's not related to writing access. It's because you are pointing not to PGDATA.
We will fix it in #120
