### ISSUE TITLE
Segmentation violation when execute wal-g  backup-push

### ISSUE THREAD

**Issue by jmvizcainoio** [wal-g/wal-g#470]
**Version**

wal-g version v0.2.13	271f64f	2019.10.15_19:01:18	PostgreSQL
postgres (PostgreSQL) 11.5 (Debian 11.5-3.pgdg90+1)
Stolon cluster deployed in a k8s cluster 1.15

**config**

postgresql.conf

```
max_wal_size = '1GB'
max_connections = '101'
wal_level = 'replica'
hot_standby = 'on'
max_wal_senders = '47'
lc_messages = 'en_US.utf8'
min_wal_size = '80MB'
synchronous_standby_names = ''
archive_command = './wal-g wal-push /stolon-data/postgres/pg_wal/'
shared_buffers = '128MB'
dynamic_shared_memory_type = 'posix'
lc_monetary = 'en_US.utf8'
archive_mode = 'on'
datestyle = 'iso, mdy'
unix_socket_directories = '/tmp'
port = '5432'
log_timezone = 'Etc/UTC'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
listen_addresses = '10.1.0.43'
timezone = 'Etc/UTC'
wal_keep_segments = '8'
max_replication_slots = '20'
default_text_search_config = 'pg_catalog.english'
```

Postgres credentials are setting using environment variables and the storage bucket is in google cloud storare.

When execute  `./wal-g  backup-push /stolon-data/postgres/pg_wal/` from the master node i'm getting this.

```
INFO: 2019/11/15 10:35:00.593355 Doing full backup.
INFO: 2019/11/15 10:35:00.677849 Calling pg_start_backup()
INFO: 2019/11/15 10:35:02.679789 Walking ...
INFO: 2019/11/15 10:35:02.684278 Starting part 1 ...
INFO: 2019/11/15 10:35:02.691082 Finished writing part 1.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bfa4b]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).UploadPgControl(0xc0001400e0, 0x16564f1, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:402 +0x3b
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0000a95c0, 0xc0003787c0, 0x1c, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:169 +0x6ea
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x2288c00, 0xc000321c90, 0x1, 0x1)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x2288c00, 0xc000321c70, 0x1, 0x1, 0x2288c00, 0xc000321c70)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x22897e0, 0x1, 0x22884e0, 0xc000311f78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x22897e0, 0x916cc0, 0xc000088058)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

In the bucket there are just one file.

`gs://bucket/basebackups_005/base_000000010000000000000005/tar_partitions/part_001.tar.lz4`

Any suggestions of what happens?

Many thanks

**Comment by gulywwx** [comment]
I reckon /stolon-data/postgres is your PG HOME dir.
Have you tried  ./wal-g backup-push /stolon-data/postgres

**Comment by jmvizcainoio** [comment]
Hi @gulywwx 

Thanks for the quick reply.

Using the path as you say work perfect.

```bash
INFO: 2019/11/15 12:23:29.723142 Doing full backup.
INFO: 2019/11/15 12:23:29.811504 Calling pg_start_backup()
INFO: 2019/11/15 12:23:30.431114 Walking ...
INFO: 2019/11/15 12:23:30.439027 Starting part 1 ...
INFO: 2019/11/15 12:23:43.054358 Finished writing part 1.
INFO: 2019/11/15 12:23:43.933470 Starting part 2 ...
INFO: 2019/11/15 12:23:43.933574 /global/pg_control
INFO: 2019/11/15 12:23:43.948507 Finished writing part 2.
INFO: 2019/11/15 12:23:43.962728 Calling pg_stop_backup()
INFO: 2019/11/15 12:23:46.823527 Starting part 3 ...
INFO: 2019/11/15 12:23:46.825559 backup_label
INFO: 2019/11/15 12:23:46.825606 tablespace_map
INFO: 2019/11/15 12:23:46.826623 Finished writing part 3.
INFO: 2019/11/15 12:23:47.336743 Wrote backup with name base_000000020000000000000018
```

Many thanks
