### ISSUE TITLE
Backup to non-amazon S3 Store not working

### ISSUE THREAD

**Issue by guruguruguru** [wal-g/wal-g#481]
Does anyone have an idea what is happening here?

```INFO: 2019/11/29 11:56:20.205671 Doing full backup.
WARNING: 2019/11/29 11:56:20.211300 It seems your archive_mode is not enabled. This will cause inconsistent backup. Please consider configuring WAL archiving.
INFO: 2019/11/29 11:56:20.312701 Walking ...
INFO: 2019/11/29 11:56:20.312888 Starting part 1 ...
INFO: 2019/11/29 11:56:20.582178 Finished writing part 1.
ERROR: 2019/11/29 11:56:25.804218 failed to upload 'basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4' to bucket 'test': SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: tx39da02f033524b81a17a6-005de10769, host id: tx39da02f033524b81a17a6-005de10769
ERROR: 2019/11/29 11:56:25.804232 upload: could not upload 'base_000000010000000000000002/tar_partitions/part_001.tar.lz4'
ERROR: 2019/11/29 11:56:25.804237 failed to upload 'basebackups_005/base_000000010000000000000002/tar_partitions/part_001.tar.lz4' to bucket 'test': SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: tx39da02f033524b81a17a6-005de10769, host id: tx39da02f033524b81a17a6-005de10769
ERROR: 2019/11/29 11:56:25.804246 Unable to complete uploads
command terminated with exit code 1
```

I have set AWS_ENDPOINT, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_S3_FORCE_PATH_STYLE (as our S3 Store is not supporting the subdomain style).

I can access the S3 from my local machine using s3fs fuse driver with the same credentials.

Thanks,
Dennis

**Comment by x4m** [comment]
Hi Dennis!

Last time when I got this error was when I mistype AWS_SECRET_ACCESS_KEY, added whitespace at the end.

**Comment by guruguruguru** [comment]
Hi @x4m,
I am not sure what aws/s3 implementation we are using but I will find out on Monday. I have double checked the credentials and they are correct.

Thanks,
Dennis

**Comment by guruguruguru** [comment]
@x4m is there an option to log the calls against the S3?

**Comment by x4m** [comment]
you can set WALG_LOG_LEVEL=DEVEL
or use strace
or modify source codes, the compilation is not that hard....

**Comment by keefien** [comment]
Hi,
@guruguruguru did you find out anything regarding this issue?
I'm facing exactly the same behavior using Ceph S3 Endpoint. Bucket is definitely there, also subdir already exists and contains some files.

Using the DEVEL Log Level didn't showed anything that helped me out:

`ERROR: 2020/08/06 10:20:24.357819 NotFound: Not Found
status code: 404, request id: , host id:
failed to upload 'dcqcnpf/basebackups_005/base_00000001000000000000002D/tar_partitions/part_001.tar.lz4' to bucket 'backup'
github.com/wal-g/storages/s3.(*Uploader).upload
/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3/uploader.go:67
github.com/wal-g/storages/s3.(*Folder).PutObject
/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3/folder.go:131
github.com/wal-g/wal-g/internal.(*Uploader).Upload
/home/travis/gopath/src/github.com/wal-g/wal-g/internal/uploader.go:81
github.com/wal-g/wal-g/internal.(*StorageTarBall).startUpload.func1
/home/travis/gopath/src/github.com/wal-g/wal-g/internal/storage_tar_ball.go:82
runtime.goexit
/home/travis/.gimme/versions/go1.13.9.linux.amd64/src/runtime/asm_amd64.s:1357
ERROR: 2020/08/06 10:20:24.357832 upload: could not upload 'base_00000001000000000000002D/tar_partitions/part_001.tar.lz4'
ERROR: 2020/08/06 10:20:24.357838 failed to upload 'dcqcnpf/basebackups_005/base_00000001000000000000002D/tar_partitions/part_001.tar.lz4' to bucket 'backup': NotFound: Not Found
status code: 404, request id: , host id:
panic: packFileIntoTar: operation failed: PackFileTo: copy failed: io: read/write on closed pipe
goroutine 1171 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc000138000, 0xc0030566f0, 0x29, 0x1c08ee0, 0xc00301cdd0, 0xc002f83340, 0x0, 0x1c08b80, 0xc000568680)
/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:383 +0x10a
created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:378 +0x69b
command terminated with exit code 2`

I also double-checked the used credentials, but their passed as Env Vars and are also used for a different S3 connection using python boto, and there it works fine.

Content of my walg.json:
`{"AWS_ACCESS_KEY_ID": "<acces key>",
"AWS_SECRET_ACCESS_KEY": "<acces secret>",
"AWS_ENDPOINT": "http://192.168.10.10",
"WALG_S3_PREFIX": "s3://backup/dcqcnpf",
"WALG_LOG_LEVEL": "DEVEL",
"AWS_S3_FORCE_PATH_STYLE": "true"}`

Is there maybe an issue with encryption? Because it's just an internal http endpoint without encryption...

**Comment by keefien** [comment]
It's definitely an issue with Encryption.
I changed my config to use our public secured Endpoint which uses https and everything works fine.

@x4m is there a possibility that you guys create a new variable which controls if it's a secured or insecure connection, or maybe just check it based on leading protocol in the Endpoint?

**Comment by guruguruguru** [comment]
@keefien I did not further investigate this

**Comment by x4m** [comment]
@keefien feel free to send a PR woith proposed change. if you need assistance with code plz ask your questions here, in Telegram or Slack dev chat.

**Comment by viggy28** [comment]
I encountered this when I had the wrong `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID`.
