### ISSUE TITLE
backup-push failing to tar files

### ISSUE THREAD

**Issue by bunsenmcdubbs** [wal-g/wal-g#506]
wal-g 0.2.13 with Postgres 10

When running `backup-push`, I've run into the same error a couple times now (I believe on the same file). It is 81megabytes and definitely exists. 

```
panic: packFileIntoTar: operation failed: PackFileTo: copy failed: read /data/10/base/16385/1205055438: no data available

goroutine 317858 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc0004902a0, 0xc02c4a3280, 0x1e, 0x17fcdc0, 0xc01704c000, 0xc016ede000, 0x0, 0x17fc9a0, 0xc02a9d0000)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:375 +0x10c
created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:370 +0x5d0
```

**Comment by bunsenmcdubbs** [comment]
Turns out this was caused by filesystem corruption.

**Comment by x4m** [comment]
Hope you have backups :) (or sync replica)
I'd be happy if WAL-G cloud provide better error message. Or even proper corruption monitoring, it would be a big feature...
