### ISSUE TITLE
wal-g stuck during backup-push after "Finished writing part 1"

### ISSUE THREAD

**Issue by ssidorenko** [wal-g/wal-g#520]
While pushing to an S3 clone (exoscale).

```
postgres@postgres:/$ /usr/bin/envdir /etc/wal-g.d/env-archive/ /usr/local/bin/wal-g backup-push -f /var/lib/postgresql/data/
INFO: 2020/01/09 09:37:25.502281 Doing full backup.
INFO: 2020/01/09 09:37:25.518725 Calling pg_start_backup()
INFO: 2020/01/09 09:37:25.575039 Walking ...
INFO: 2020/01/09 09:37:25.579242 Starting part 1 ...
INFO: 2020/01/09 09:37:25.811315 Finished writing part 1.
SIGABRT: abort
PC=0x98a6e1 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x238cfe0, 0x80, 0x0, 0x0, 0x7fc700000000, 0x0, 0x0, 0x0, 0x7fffac738900, 0x93b632, ...)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x238cfe0, 0x7fc700000000, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x238cfe0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc000040000, 0x0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc00037c480)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x140a360)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0003593d8)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0003593d0)
	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/waitgroup.go:130 +0x64
github.com/wal-g/wal-g/internal.(*StorageTarBall).AwaitUploads(0xc00033ea40)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/storage_tar_ball.go:61 +0x37
github.com/wal-g/wal-g/internal.(*Bundle).FinishQueue(0xc000112460, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:155 +0xe5
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc000075aa0, 0xc000357f00, 0x18, 0x100)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:170 +0x83c
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x232b440, 0xc000266940, 0x1, 0x2)
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x83
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).execute(0x232b440, 0xc000266900, 0x2, 0x2, 0x232b440, 0xc000266900)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x232c020, 0x1, 0x232ad20, 0xc0002e9f78)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/wal-g/wal-g/vendor/github.com/spf13/cobra.(*Command).Execute(0x232c020, 0x936630, 0xc00003e0b8)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/wal-g/wal-g/cmd/pg.Execute()
	/home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:28 +0x2d
main.main()
	/home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

goroutine 6 [select]:
github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.(*worker).start(0xc0000b9540)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
created by github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view.init.0
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57

goroutine 7 [select]:
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws.SleepWithContext(0x18676e0, 0xc000038050, 0xa40830000, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/context_sleep.go:16 +0x10c
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.glob..func5(0xc0000ac480)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/corehandlers/handlers.go:202 +0x145
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run(0xc0000ac718, 0xc0000ac480)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request/handlers.go:261 +0x98
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send(0xc0000ac480, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/aws/request/request.go:511 +0x14e
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).singlePart(0xc0001d6510, 0x1856ae0, 0xc002e51f20, 0x915e01, 0xc000388000, 0x1400000)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:492 +0x1e3
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).upload(0xc0001d6510, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:378 +0x598
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.UploadWithContext(0x1400000, 0x10, 0x0, 0x2710, 0x187d7c0, 0xc00000e348, 0x0, 0x0, 0x0, 0x18676e0, ...)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:292 +0x1a9
github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.Upload(0x1400000, 0x10, 0x0, 0x2710, 0x187d7c0, 0xc00000e348, 0x0, 0x0, 0x0, 0xc000386000, ...)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/aws/aws-sdk-go/service/s3/s3manager/upload.go:263 +0xc0
github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3.(*Uploader).upload(0xc0003444d0, 0xc000034034, 0x8, 0xc00003c730, 0x4d, 0x18517a0, 0xc000373200, 0x20, 0x15b67e0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3/uploader.go:66 +0x188
github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3.(*Folder).PutObject(0xc0003444d0, 0xc00003ad40, 0x3d, 0x18517a0, 0xc000373200, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/s3/folder.go:131 +0xbe
github.com/wal-g/wal-g/internal.(*Uploader).Upload(0xc000075d40, 0xc00003ad40, 0x3d, 0x18533c0, 0xc00000e398, 0x0, 0x0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/uploader.go:110 +0xc1
github.com/wal-g/wal-g/internal.(*StorageTarBall).startUpload.func1(0xc000075d40, 0xc00003ad40, 0x3d, 0xc00000e398)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/storage_tar_ball.go:82 +0xb4
created by github.com/wal-g/wal-g/internal.(*StorageTarBall).startUpload
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/storage_tar_ball.go:79 +0x2b3

rax    0xca
rbx    0x238cea0
rcx    0x98a6e3
rdx    0x0
rdi    0x238cfe0
rsi    0x80
rbp    0x7fffac7388c8
rsp    0x7fffac738880
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xffffffffffffffff
r13    0x15a
r14    0x159
r15    0x200
rip    0x98a6e1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by ssidorenko** [comment]
Turns out I had to enable the `AWS_S3_FORCE_PATH_STYLE ` parameter to make wal-g work with exoscale SOS.

**Comment by x4m** [comment]
Hey @ssidorenko thanks for reaching out. We will be more than happy if you send us PR with improved docs so that anyone with similar problems will go short way? Or maybe we could improve wal-g output, give user some hints etc?
