### ISSUE TITLE
hang with `WALG_LIBSODIUM_KEY`

### ISSUE THREAD

**Issue by nwns** [wal-g/wal-g#632]
When `WALG_LIBSODIUM_KEY` is set, wal-push hangs.  The below is the result of a kill -ABRT on the wal-g process.

wal-g was complied in docker in an alpine-linux 3.10 base image because we run postgres on alpine-linux 3.10 in GKE production.

I have encoutered this hang with both the FILE backup and S3 (using minio as documented in wal-g documentation).  I have not tried it with GCS yet as the test cluster does not use GCS for its object store (it uses minio).

Thanks,

```git clone https://github.com/wal-g/wal-g.git wal-g -b v0.2.15 \
    && cd wal-g \
    && export GOBIN=/usr/local/bin \
    && export USE_LIBSODIUM=true \
    && make install deps pg_build pg_install \
    && cd / \
    && rm -r wal-g
```

```
SIGABRT: abort
PC=0x556a6e945e71 m=0 sigcode=0

goroutine 0 [idle]:
runtime.futex(0x556a708d7d28, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7ffc784a92d8, 0x556a6e8f4e45, ...)
	/usr/lib/go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x556a708d7d28, 0xc000000000, 0xffffffffffffffff)
	/usr/lib/go/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x556a708d7d28)
	/usr/lib/go/src/runtime/lock_futex.go:151 +0xa5
runtime.stopm()
	/usr/lib/go/src/runtime/proc.go:1936 +0xc5
runtime.findrunnable(0xc000044a00, 0x0)
	/usr/lib/go/src/runtime/proc.go:2399 +0x550
runtime.schedule()
	/usr/lib/go/src/runtime/proc.go:2525 +0x220
runtime.park_m(0xc00008bb00)
	/usr/lib/go/src/runtime/proc.go:2605 +0xa7
runtime.mcall(0x7ffc784a94d8)
	/usr/lib/go/src/runtime/asm_amd64.s:299 +0x53

goroutine 1 [select, 7 minutes]:
io.(*pipe).Write(0xc00038a0f0, 0xc000546880, 0x18, 0x18, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/pipe.go:87 +0x1d9
io.(*PipeWriter).Write(0xc0002a4058, 0xc000546880, 0x18, 0x18, 0xc00003a053, 0x20, 0x20)
	/usr/lib/go/src/io/pipe.go:153 +0x4e
github.com/wal-g/wal-g/internal/crypto/libsodium.NewWriter(0x556a6ff51140, 0xc0002a4058, 0xc000546860, 0x20, 0x20, 0x20, 0x556a6fddbdc0, 0x556a6fd85201, 0xc0002a4058)
	/wal-g/internal/crypto/libsodium/writer.go:38 +0xc4
github.com/wal-g/wal-g/internal/crypto/libsodium.(*Crypter).Encrypt(0xc0000bde00, 0x556a6ff51140, 0xc0002a4058, 0xc0005399d0, 0x556a6e8f33c8, 0x556a708f3ca0, 0x0)
	/wal-g/internal/crypto/libsodium/crypter.go:84 +0xbb
github.com/wal-g/wal-g/internal.CompressAndEncrypt(0x7f7d65849028, 0xc000228c00, 0x556a6ff5f5a0, 0x556a708f3d28, 0x556a6ff5d360, 0xc0000bde00, 0xc000228c00, 0x556a6e8f31fe)
	/wal-g/internal/compress_and_encrypt.go:36 +0x2cb
github.com/wal-g/wal-g/internal.(*Uploader).UploadFile(0xc0000d62d0, 0x556a6ff5d2a0, 0xc000228c00, 0x556a6ff51640, 0xc0002a4048)
	/wal-g/internal/uploader.go:71 +0xbf
github.com/wal-g/wal-g/internal.(*WalUploader).UploadWalFile(0xc000545050, 0x556a6ff5ed20, 0xc0002a4048, 0x0, 0x0)
	/wal-g/internal/wal_uploader.go:59 +0x1ed
github.com/wal-g/wal-g/internal.uploadWALFile(0xc000545050, 0x7ffc784aa7be, 0x1f, 0xc000545001, 0x1, 0xc0000d6320)
	/wal-g/internal/wal_push_handler.go:74 +0x14d
github.com/wal-g/wal-g/internal.HandleWALPush(0xc000545050, 0x7ffc784aa7be, 0x1f)
	/wal-g/internal/wal_push_handler.go:50 +0x2db
github.com/wal-g/wal-g/cmd/pg.glob..func9(0x556a7086b720, 0xc0004e2220, 0x1, 0x1)
	/wal-g/cmd/pg/wal_push.go:27 +0x207
github.com/spf13/cobra.(*Command).execute(0x556a7086b720, 0xc0004e21f0, 0x1, 0x1, 0x556a7086b720, 0xc0004e21f0)
	/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2b0
github.com/spf13/cobra.(*Command).ExecuteC(0x556a7086afa0, 0xc000539f68, 0x556a6f4bf220, 0x556a7086afa0)
	/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
	/wal-g/cmd/pg/pg.go:29 +0x34
main.main()
	/wal-g/main/pg/main.go:8 +0x22

goroutine 19 [syscall, 7 minutes]:
os/signal.signal_recv(0x0)
	/usr/lib/go/src/runtime/sigqueue.go:139 +0x9e
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:23 +0x24
created by os/signal.init.0
	/usr/lib/go/src/os/signal/signal_unix.go:29 +0x43

goroutine 21 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00038a870)
	/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x102
created by go.opencensus.io/stats/view.init.0
	/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x59

rax    0xca
rbx    0x556a708d7be0
rcx    0x556a6e945e73
rdx    0x0
rdi    0x556a708d7d28
rsi    0x80
rbp    0x7ffc784a92a0
rsp    0x7ffc784a9258
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x1
r14    0x1
r15    0xc0002c4ba0
rip    0x556a6e945e71
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

**Comment by nwns** [comment]
Also without the `WALG_LIBSODIUM_KEY` it it is working correctly.

Current config on test cluster
```
AWS_ACCESS_KEY_ID='Fz5DPRYtA13Rea8H'
AWS_ENDPOINT='http://object:9000'
AWS_REGION='us-east-1'
AWS_S3_FORCE_PATH_STYLE='true'
AWS_SECRET_ACCESS_KEY='LXvMsluotBDWQXJe9FNoX3PXZuXbH2WG'
WALG_COMPRESSION_METHOD='lzma'
WALG_PREVENT_WAL_OVERWRITE='true'
WALG_S3_PREFIX='s3://postgres'
```

**Comment by YKatrechko** [comment]
Have the same issue with `wal-g wal-push` command.
wal-g was complied in docker in an debian-stretch image.

Commands `wal-g backup-push` and `wal-g backup-fetch` work as expected. I get encripted files in Azure Container. 

use this workaround:
```
"archive_command": "WALG_LIBSODIUM_KEY= wal-g wal-push %p"
"restoreCommand": "WALG_LIBSODIUM_KEY= wal-g wal-fetch \"%f\" \"%p\""
```
env:
```
DEBUG: 2020/04/27 14:58:37.881692 AZURE_STORAGE_ACCOUNT=walgbackup
DEBUG: 2020/04/27 14:58:37.881718 AZURE_ACCOUNT_KEY=xxxxxxxxxxxxxxxxxxxx==
DEBUG: 2020/04/27 14:58:37.881805 WALG_LIBSODIUM_KEY=AcEyb1234asdf1234@ASDfgh
DEBUG: 2020/04/27 14:58:37.881919 WALG_COMPRESSION_METHOD=brotli
DEBUG: 2020/04/27 14:58:37.881594 WALG_AZ_PREFIX=azure://walgbackup/postgres
DEBUG: 2020/04/27 14:58:37.882049 WALG_TAR_SIZE_THRESHOLD=1073741823
DEBUG: 2020/04/27 14:58:37.882062 WALG_DOWNLOAD_CONCURRENCY=10
DEBUG: 2020/04/27 14:58:37.882065 WALG_USE_WAL_DELTA=false
DEBUG: 2020/04/27 14:58:37.882071 WALG_PREVENT_WAL_OVERWRITE=false
DEBUG: 2020/04/27 14:58:37.882073 WALG_UPLOAD_DISK_CONCURRENCY=1
DEBUG: 2020/04/27 14:58:37.882077 WALG_DELTA_MAX_STEPS=0
DEBUG: 2020/04/27 14:58:37.882083 WALG_UPLOAD_QUEUE=2
DEBUG: 2020/04/27 14:58:37.882086 WALG_UPLOAD_CONCURRENCY=16
```

**Comment by YKatrechko** [comment]
As I see [tests/crypto_test.sh](https://github.com/wal-g/wal-g/blob/master/docker/pg_tests/scripts/tests/crypto_test.sh) has no libsodium tests. Could you please add required tests

**Comment by defntvdm** [comment]
@nwns, hi, please close PR if everything is ok.

**Comment by nwns** [comment]
Apologies, I apparently missed all of the notifications about this.

Yes, building wal-g from master has fixed the hang that I was experiencing.
