### ISSUE TITLE
Invalid memory address or nil pointer dereference, signal SIGSEGV: segmentation violation code

### ISSUE THREAD

**Issue by Dmitri191** [wal-g/wal-g#689]
Hello!

Sometimes we have problems with making backup PostgreSQL.
After start backup PostgreSQL we recieved error:
Jun 25 01:00:01 INFO: 2020/06/25 01:00:01.812187 Delta will be made from full backup.
Jun 25 01:00:01 panic: runtime error: invalid memory address or nil pointer dereference
Jun 25 01:00:01 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150bdb6]
Jun 25 01:00:01
Jun 25 01:00:01 goroutine 1 [running]:
Jun 25 01:00:01 github.com/wal-g/wal-g/internal.HandleBackupPush(0xc00049b840, 0x7ffda80cee90, 0x24, 0x0)
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:234 +0x686
Jun 25 01:00:01 github.com/wal-g/wal-g/cmd/pg.glob..func4(0x267e6c0, 0xc0004a01e0, 0x1, 0x3)
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x86
Jun 25 01:00:01 github.com/spf13/cobra.(*Command).execute(0x267e6c0, 0xc00026fe80, 0x3, 0x4, 0x267e6c0, 0xc00026fe80)
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
Jun 25 01:00:01 github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
Jun 25 01:00:01 github.com/spf13/cobra.(*Command).Execute(...)
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
Jun 25 01:00:01 github.com/wal-g/wal-g/cmd/pg.Execute()
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:29 +0x31
Jun 25 01:00:01 main.main()
Jun 25 01:00:01         /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
Jun 25 01:00:01

But after start backup again with same command we received OK:
Jun 25 02:02:23 INFO: 2020/06/25 02:02:23.852860 Delta backup from base_000000010000000400000053 with LSN 453000028.
Jun 25 02:02:23 INFO: 2020/06/25 02:02:23.876878 Calling pg_start_backup()
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.022326 Walking ...
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.022731 Starting part 1 ...
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.060324 Finished writing part 1.
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.104796 Starting part 2 ...
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.104841 /global/pg_control
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.105377 Finished writing part 2.
Jun 25 02:02:24 INFO: 2020/06/25 02:02:24.106632 Calling pg_stop_backup()
Jun 25 02:02:25 INFO: 2020/06/25 02:02:25.167484 Starting part 3 ...
Jun 25 02:02:25 INFO: 2020/06/25 02:02:25.173081 backup_label
Jun 25 02:02:25 INFO: 2020/06/25 02:02:25.173178 tablespace_map
Jun 25 02:02:25 INFO: 2020/06/25 02:02:25.173264 Finished writing part 3.
Jun 25 02:02:25 INFO: 2020/06/25 02:02:25.311130 Wrote backup with name base_0000000100000004000000EB_D_000000010000000400000053
Jun 25 02:02:25

Can you help me resolve this proplem?

**Comment by x4m** [comment]
hi! thanks for reporting!

Seems like its' a bug
here https://github.com/wal-g/wal-g/blob/master/internal/backup_push_handler.go#L234
we try to detect if we can make delta backup and fail....
it only happens if we do it with option FROM_FULL
Can you please send a PR with fix like this?
https://github.com/wal-g/wal-g/blob/master/internal/backup_push_handler.go#L222

**Comment by Dmitri191** [comment]
I had found a same issue - https://github.com/wal-g/wal-g/issues/406.
It has PR - https://github.com/wal-g/wal-g/pull/408.

**Comment by x4m** [comment]
@Dmitri191 yup, merged, thanks!
