### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Tri0L** [wal-g/wal-g#798]
Version:
```
~$ /usr/local/bin/wal-g  --version
wal-g version v0.2.15   f6abd0c 2020.03.24_11:58:03     PostgreSQL
```

Config:
```
{
    "WALG_LOG_LEVEL":"NORMAL",
    "PGPORT":"5432",
    "PGUSER":"postgres",
    "PGHOST":"/var/run/postgresql",
    "WALE_S3_PREFIX": "s3://bucket/directory",
    "AWS_ENDPOINT": "https://storage.yandexcloud.net",
    "AWS_REGION": "ru-central1",
    "AWS_ACCESS_KEY_ID": "*****",
    "AWS_SECRET_ACCESS_KEY": "********",
    "WALG_DELTA_MAX_STEPS": "6",
    "WALG_UPLOAD_CONCURRENCY": "6",
    "WALG_S3_STORAGE_CLASS": "COLD",
    "WALG_DELTA_ORIGIN": "LATEST_FULL"
}
```

Problem:
```
~$ /usr/local/bin/wal-g backup-push /var/lib/postgresql/11/main/
INFO: 2020/11/04 18:51:33.821021 Delta will be made from full backup.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150bdb6]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0004c4230, 0x7ffdb258786e, 0x1c, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:234 +0x686
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x267e6c0, 0xc0004c4130, 0x1, 0x1)
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x86
github.com/spf13/cobra.(*Command).execute(0x267e6c0, 0xc0004c4110, 0x1, 0x1, 0x267e6c0, 0xc0004c4110)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:29 +0x31
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20

$ /usr/local/bin/wal-g backup-list
name                          last_modified        wal_segment_backup_start
base_0000000100003537000000EB 2020-11-02T21:34:58Z 0000000100003537000000EB

$ /usr/local/bin/wal-g backup-push /var/lib/postgresql/11/main/ -f
INFO: 2020/11/04 18:53:28.122122 Doing full backup.
INFO: 2020/11/04 18:53:28.221248 Calling pg_start_backup()
INFO: 2020/11/04 18:53:54.010895 Walking ...
INFO: 2020/11/04 18:53:54.011353 Starting part 1 ...
INFO: 2020/11/04 18:54:13.594785 Finished writing part 1.
INFO: 2020/11/04 18:54:13.594823 Starting part 2 ...
INFO: 2020/11/04 18:54:32.130287 Finished writing part 2.
INFO: 2020/11/04 18:54:32.130326 Starting part 3 ...
INFO: 2020/11/04 18:54:48.530706 Finished writing part 3.
INFO: 2020/11/04 18:54:48.530753 Starting part 4 ...
INFO: 2020/11/04 18:55:04.924655 Finished writing part 4.
INFO: 2020/11/04 18:55:04.924692 Starting part 5 ...
INFO: 2020/11/04 18:55:35.028615 Finished writing part 5.
INFO: 2020/11/04 18:55:35.028664 Starting part 6 ...
INFO: 2020/11/04 18:55:51.485910 Finished writing part 6.
INFO: 2020/11/04 18:55:51.486002 Starting part 7 ...
INFO: 2020/11/04 18:56:08.040227 Finished writing part 7.
INFO: 2020/11/04 18:56:08.040267 Starting part 8 ...
INFO: 2020/11/04 18:56:24.617405 Finished writing part 8.
INFO: 2020/11/04 18:56:24.617460 Starting part 9 ...
INFO: 2020/11/04 18:56:45.870645 Finished writing part 9.
INFO: 2020/11/04 18:56:45.870697 Starting part 10 ...
INFO: 2020/11/04 18:57:03.181314 Finished writing part 10.
INFO: 2020/11/04 18:57:03.181367 Starting part 11 ...
INFO: 2020/11/04 18:57:30.798715 Finished writing part 11.
INFO: 2020/11/04 18:57:30.798754 Starting part 12 ...
INFO: 2020/11/04 18:57:51.037007 Finished writing part 12.
INFO: 2020/11/04 18:57:51.037048 Starting part 13 ...
INFO: 2020/11/04 18:58:07.438492 Finished writing part 13.
INFO: 2020/11/04 18:58:07.438527 Starting part 14 ...
INFO: 2020/11/04 18:58:34.038288 Finished writing part 14.
INFO: 2020/11/04 18:58:34.038321 Starting part 15 ...
INFO: 2020/11/04 18:58:59.973264 Finished writing part 15.
INFO: 2020/11/04 18:58:59.973302 Starting part 16 ...
INFO: 2020/11/04 18:59:27.550044 Finished writing part 16.
INFO: 2020/11/04 18:59:27.550099 Starting part 17 ...
INFO: 2020/11/04 18:59:44.014166 Finished writing part 17.
INFO: 2020/11/04 18:59:44.014202 Starting part 18 ...
INFO: 2020/11/04 19:00:00.561946 Finished writing part 18.
INFO: 2020/11/04 19:00:00.561991 Starting part 19 ...
INFO: 2020/11/04 19:00:17.147863 Finished writing part 19.
INFO: 2020/11/04 19:00:17.147909 Starting part 20 ...
INFO: 2020/11/04 19:00:42.134789 Finished writing part 20.
INFO: 2020/11/04 19:00:42.134845 Starting part 21 ...
INFO: 2020/11/04 19:00:58.568703 Finished writing part 21.
INFO: 2020/11/04 19:00:58.568737 Starting part 22 ...
INFO: 2020/11/04 19:01:15.019977 Finished writing part 22.
INFO: 2020/11/04 19:01:15.020019 Starting part 23 ...
INFO: 2020/11/04 19:01:31.461989 Finished writing part 23.
INFO: 2020/11/04 19:01:31.462019 Starting part 24 ...
INFO: 2020/11/04 19:01:53.188752 Finished writing part 24.
INFO: 2020/11/04 19:01:53.188785 Starting part 25 ...
INFO: 2020/11/04 19:02:09.744140 Finished writing part 25.
INFO: 2020/11/04 19:02:09.744175 Starting part 26 ...
INFO: 2020/11/04 19:02:37.415572 Finished writing part 26.
INFO: 2020/11/04 19:02:37.415641 Starting part 27 ...
INFO: 2020/11/04 19:03:05.151963 Finished writing part 27.
INFO: 2020/11/04 19:03:05.152018 Starting part 28 ...
INFO: 2020/11/04 19:03:28.353964 Finished writing part 28.
INFO: 2020/11/04 19:03:28.353994 Starting part 29 ...
INFO: 2020/11/04 19:03:43.918575 Finished writing part 29.
INFO: 2020/11/04 19:03:43.918613 Starting part 30 ...
INFO: 2020/11/04 19:04:01.746883 Finished writing part 30.
INFO: 2020/11/04 19:04:01.746918 Starting part 31 ...
INFO: 2020/11/04 19:04:22.296627 Finished writing part 31.
INFO: 2020/11/04 19:04:22.296663 Starting part 32 ...
INFO: 2020/11/04 19:04:40.806691 Finished writing part 32.
INFO: 2020/11/04 19:04:40.806760 Starting part 33 ...
INFO: 2020/11/04 19:05:02.488028 Finished writing part 33.
INFO: 2020/11/04 19:05:02.488062 Starting part 34 ...
INFO: 2020/11/04 19:05:30.200598 Finished writing part 34.
INFO: 2020/11/04 19:05:30.200628 Starting part 35 ...
INFO: 2020/11/04 19:06:01.824476 Finished writing part 35.
INFO: 2020/11/04 19:06:01.824511 Starting part 36 ...
INFO: 2020/11/04 19:06:36.584563 Finished writing part 36.
INFO: 2020/11/04 19:06:36.584608 Starting part 37 ...
INFO: 2020/11/04 19:07:00.509402 Finished writing part 37.
INFO: 2020/11/04 19:07:00.509435 Starting part 38 ...
INFO: 2020/11/04 19:07:32.142401 Finished writing part 38.
INFO: 2020/11/04 19:07:32.142455 Starting part 39 ...
INFO: 2020/11/04 19:07:49.868547 Finished writing part 39.
INFO: 2020/11/04 19:07:49.868600 Starting part 40 ...
INFO: 2020/11/04 19:08:22.452854 Finished writing part 40.
INFO: 2020/11/04 19:08:22.452886 Starting part 41 ...
INFO: 2020/11/04 19:08:45.486266 Finished writing part 41.
INFO: 2020/11/04 19:08:45.486324 Starting part 42 ...
INFO: 2020/11/04 19:09:04.733923 Finished writing part 42.
INFO: 2020/11/04 19:09:04.733970 Starting part 43 ...
INFO: 2020/11/04 19:09:21.577753 Finished writing part 43.
INFO: 2020/11/04 19:09:21.577794 Starting part 44 ...
INFO: 2020/11/04 19:09:38.979218 Finished writing part 44.
INFO: 2020/11/04 19:09:38.979267 Starting part 45 ...
INFO: 2020/11/04 19:10:10.295652 Finished writing part 45.
INFO: 2020/11/04 19:10:10.295704 Starting part 46 ...
INFO: 2020/11/04 19:10:27.950801 Finished writing part 46.
INFO: 2020/11/04 19:10:27.950840 Starting part 47 ...
INFO: 2020/11/04 19:10:44.399554 Finished writing part 47.
INFO: 2020/11/04 19:10:44.399587 Starting part 48 ...
INFO: 2020/11/04 19:11:00.847406 Finished writing part 48.
INFO: 2020/11/04 19:11:00.847462 Starting part 49 ...
INFO: 2020/11/04 19:11:21.707116 Finished writing part 49.
INFO: 2020/11/04 19:11:21.707153 Starting part 50 ...
INFO: 2020/11/04 19:11:39.531121 Finished writing part 50.
INFO: 2020/11/04 19:11:39.531162 Starting part 51 ...
INFO: 2020/11/04 19:12:12.470334 Finished writing part 51.
INFO: 2020/11/04 19:12:12.470379 Starting part 52 ...
INFO: 2020/11/04 19:12:36.019056 Finished writing part 52.
INFO: 2020/11/04 19:12:36.019104 Starting part 53 ...
INFO: 2020/11/04 19:12:52.470704 Finished writing part 53.
INFO: 2020/11/04 19:12:52.470745 Starting part 54 ...
INFO: 2020/11/04 19:13:15.567292 Finished writing part 54.
INFO: 2020/11/04 19:13:15.567339 Starting part 55 ...
INFO: 2020/11/04 19:13:32.068636 Finished writing part 55.
INFO: 2020/11/04 19:13:32.068669 Starting part 56 ...
INFO: 2020/11/04 19:13:51.342526 Finished writing part 56.
INFO: 2020/11/04 19:13:51.342576 Starting part 57 ...
INFO: 2020/11/04 19:14:09.217342 Finished writing part 57.
INFO: 2020/11/04 19:14:09.217394 Starting part 58 ...
INFO: 2020/11/04 19:14:25.670339 Finished writing part 58.
INFO: 2020/11/04 19:14:25.670380 Starting part 59 ...
INFO: 2020/11/04 19:14:50.972041 Finished writing part 59.
INFO: 2020/11/04 19:14:50.972086 Starting part 60 ...
INFO: 2020/11/04 19:15:07.466099 Finished writing part 60.
INFO: 2020/11/04 19:15:07.466138 Starting part 61 ...
INFO: 2020/11/04 19:15:34.678656 Finished writing part 61.
INFO: 2020/11/04 19:15:34.678728 Starting part 62 ...
INFO: 2020/11/04 19:15:56.962042 Finished writing part 62.
INFO: 2020/11/04 19:15:56.962085 Starting part 63 ...
INFO: 2020/11/04 19:16:13.426486 Finished writing part 63.
INFO: 2020/11/04 19:16:13.426528 Starting part 64 ...
INFO: 2020/11/04 19:16:35.449074 Finished writing part 64.
INFO: 2020/11/04 19:16:35.449110 Starting part 65 ...
INFO: 2020/11/04 19:16:51.958691 Finished writing part 65.
INFO: 2020/11/04 19:16:51.958742 Starting part 66 ...
INFO: 2020/11/04 19:17:08.431149 Finished writing part 66.
INFO: 2020/11/04 19:17:08.431216 Starting part 67 ...
INFO: 2020/11/04 19:17:24.917970 Finished writing part 67.
INFO: 2020/11/04 19:17:24.918026 Starting part 68 ...
INFO: 2020/11/04 19:17:41.376203 Finished writing part 68.
INFO: 2020/11/04 19:17:41.376266 Starting part 69 ...
INFO: 2020/11/04 19:18:28.137427 Finished writing part 69.
INFO: 2020/11/04 19:18:28.137477 Starting part 70 ...
INFO: 2020/11/04 19:19:00.375522 Finished writing part 70.
INFO: 2020/11/04 19:19:00.375565 Starting part 71 ...
INFO: 2020/11/04 19:19:25.001864 Finished writing part 71.
INFO: 2020/11/04 19:19:25.001916 Starting part 72 ...
INFO: 2020/11/04 19:19:51.038200 Finished writing part 72.
INFO: 2020/11/04 19:19:51.038307 Starting part 73 ...
INFO: 2020/11/04 19:20:11.144909 Finished writing part 73.
INFO: 2020/11/04 19:20:11.144962 Starting part 74 ...
INFO: 2020/11/04 19:20:28.246676 Finished writing part 74.
INFO: 2020/11/04 19:20:28.246722 Starting part 75 ...
INFO: 2020/11/04 19:20:44.791069 Finished writing part 75.
INFO: 2020/11/04 19:20:44.791111 Starting part 76 ...
INFO: 2020/11/04 19:21:08.382904 Finished writing part 76.
INFO: 2020/11/04 19:21:08.383024 Starting part 77 ...
INFO: 2020/11/04 19:21:24.824621 Finished writing part 77.
INFO: 2020/11/04 19:21:24.824656 Starting part 78 ...
INFO: 2020/11/04 19:21:41.258753 Finished writing part 78.
INFO: 2020/11/04 19:21:41.258790 Starting part 79 ...
INFO: 2020/11/04 19:21:57.699014 Finished writing part 79.
INFO: 2020/11/04 19:21:57.699054 Starting part 80 ...
INFO: 2020/11/04 19:22:14.140628 Finished writing part 80.
INFO: 2020/11/04 19:22:14.140666 Starting part 81 ...
INFO: 2020/11/04 19:22:30.638335 Finished writing part 81.
INFO: 2020/11/04 19:22:30.638368 Starting part 82 ...
INFO: 2020/11/04 19:22:47.380903 Finished writing part 82.
INFO: 2020/11/04 19:22:47.380940 Starting part 83 ...
INFO: 2020/11/04 19:23:12.691013 Finished writing part 83.
INFO: 2020/11/04 19:23:12.691054 Starting part 84 ...
INFO: 2020/11/04 19:23:29.175015 Finished writing part 84.
INFO: 2020/11/04 19:23:29.175054 Starting part 85 ...
INFO: 2020/11/04 19:23:51.446952 Finished writing part 85.
INFO: 2020/11/04 19:23:51.447019 Starting part 86 ...
INFO: 2020/11/04 19:24:07.894515 Finished writing part 86.
INFO: 2020/11/04 19:24:07.894555 Starting part 87 ...
INFO: 2020/11/04 19:24:24.416468 Finished writing part 87.
INFO: 2020/11/04 19:24:24.416507 Starting part 88 ...
INFO: 2020/11/04 19:24:44.141219 Finished writing part 88.
INFO: 2020/11/04 19:24:44.141280 Starting part 89 ...
INFO: 2020/11/04 19:25:00.596693 Finished writing part 89.
INFO: 2020/11/04 19:25:00.596758 Starting part 90 ...
INFO: 2020/11/04 19:25:17.032429 Finished writing part 90.
INFO: 2020/11/04 19:25:17.032465 Starting part 91 ...
INFO: 2020/11/04 19:25:33.481960 Finished writing part 91.
INFO: 2020/11/04 19:25:33.482004 Starting part 92 ...
INFO: 2020/11/04 19:25:49.932408 Finished writing part 92.
INFO: 2020/11/04 19:25:49.932465 Starting part 93 ...
INFO: 2020/11/04 19:26:19.786399 Finished writing part 93.
INFO: 2020/11/04 19:26:19.786438 Starting part 94 ...
INFO: 2020/11/04 19:26:36.248806 Finished writing part 94.
INFO: 2020/11/04 19:26:36.248856 Starting part 95 ...
INFO: 2020/11/04 19:27:00.712801 Finished writing part 95.
INFO: 2020/11/04 19:27:00.712833 Starting part 96 ...
INFO: 2020/11/04 19:27:27.187442 Finished writing part 96.
INFO: 2020/11/04 19:27:27.187495 Starting part 97 ...
INFO: 2020/11/04 19:27:46.489178 Finished writing part 97.
INFO: 2020/11/04 19:27:46.489214 Starting part 98 ...
INFO: 2020/11/04 19:28:17.731112 Finished writing part 98.
INFO: 2020/11/04 19:28:17.731169 Starting part 99 ...
INFO: 2020/11/04 19:28:27.978296 Finished writing part 99.
INFO: 2020/11/04 19:28:29.006619 Starting part 100 ...
INFO: 2020/11/04 19:28:29.006677 /global/pg_control
INFO: 2020/11/04 19:28:29.008841 Finished writing part 100.
INFO: 2020/11/04 19:28:29.010944 Calling pg_stop_backup()
INFO: 2020/11/04 19:28:30.031778 Starting part 101 ...
INFO: 2020/11/04 19:28:30.033091 backup_label
INFO: 2020/11/04 19:28:30.033272 tablespace_map
INFO: 2020/11/04 19:28:30.033441 Finished writing part 101.
INFO: 2020/11/04 19:28:30.604798 Wrote backup with name base_0000000100003566000000EE

~$ /usr/local/bin/wal-g backup-list
name                          last_modified        wal_segment_backup_start
base_0000000100003537000000EB 2020-11-02T21:34:58Z 0000000100003537000000EB
base_0000000100003566000000EE 2020-11-04T16:28:30Z 0000000100003566000000EE

~$ /usr/local/bin/wal-g backup-push /var/lib/postgresql/11/main/
INFO: 2020/11/04 21:36:05.718914 Delta will be made from full backup.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x150bdb6]

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.HandleBackupPush(0xc0004d3b60, 0x7ffc3729886e, 0x1c, 0x0)
        /home/travis/gopath/src/github.com/wal-g/wal-g/internal/backup_push_handler.go:234 +0x686
github.com/wal-g/wal-g/cmd/pg.glob..func4(0x267e6c0, 0xc0004d2120, 0x1, 0x1)
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/backup_push.go:27 +0x86
github.com/spf13/cobra.(*Command).execute(0x267e6c0, 0xc0004d2100, 0x1, 0x1, 0x267e6c0, 0xc0004d2100)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x267d7c0, 0x9ca6fa, 0x2691b40, 0xc000000180)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/pg.Execute()
        /home/travis/gopath/src/github.com/wal-g/wal-g/cmd/pg/pg.go:29 +0x31
main.main()
        /home/travis/gopath/src/github.com/wal-g/wal-g/main/pg/main.go:8 +0x20
```

**Comment by Tri0L** [comment]
Fixed in https://github.com/wal-g/wal-g/pull/408
