### ISSUE TITLE
Backup to Swift storage doesn't work

### ISSUE THREAD

**Issue by balbaev** [wal-g/wal-g#801]
Suddenly backup-push to swift storage doesn't work with the following:
````
INFO: 2020/11/08 17:42:11.469357 Delta backup from base_000000050000010E000000FA_D_000000050000010D0000005F with LSN 10efa000028. 
INFO: 2020/11/08 17:42:11.488799 Calling pg_start_backup()
INFO: 2020/11/08 17:42:11.535293 Walking ...
INFO: 2020/11/08 17:42:11.535644 Starting part 1 ...
ERROR: 2020/11/08 17:43:26.217078 Swift error : Unable to write content.: Timeout when reading or writing data
ERROR: 2020/11/08 17:43:26.217129 upload: could not upload 'base_0000000700000110000000C2_D_000000050000010E000000FA/tar_partitions/part_001.tar.br'
ERROR: 2020/11/08 17:43:26.217147 Swift error : Unable to write content.: Timeout when reading or writing data
panic: packFileIntoTar: operation failed: PackFileTo: copy failed: io: read/write on closed pipe

goroutine 1350 [running]:
github.com/wal-g/wal-g/internal.(*Bundle).handleTar.func1(0xc0006560e0, 0xc0002a4060, 0x30, 0x1e02540, 0xc000391ba0, 0xc0001020e0, 0x1, 0x1e02120, 0xc0002eaac0)
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:386 +0x10a
created by github.com/wal-g/wal-g/internal.(*Bundle).handleTar
	/home/travis/gopath/src/github.com/wal-g/wal-g/internal/bundle.go:381 +0x69b
````
wal-g v0.2.17
defined WALG_COMPRESSION_METHOD as brotli and WALG_LIBSODIUM_KEY

wal-push, wal-fetch and backup-fetch are working correctly

**Comment by x4m** [comment]
Chances are we are not setting some settings correctly for SWIFT...

**Comment by balbaev** [comment]
Solved by increasing GOSWIFT_TIMEOUT to something like 300s. Default value of GOSWIFT_TIMEOUT is 60s and sometimes it's not enough to do all the stuff with backup chunk.
