### ISSUE TITLE
backup delete fails with panic 

### ISSUE THREAD

**Issue by reshke** [wal-g/wal-g#802]
```panic: runtime error: slice bounds out of range [:45] with length 42

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.isPermanent(...)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/internal/delete_handler.go:391
github.com/wal-g/wal-g/internal.DeleteBeforeTarget.func1(0x1c42d00, 0xc000b35d70, 0x41)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/internal/delete_handler.go:342 +0x175
github.com/wal-g/storages/storage.DeleteObjectsWhere(0x1c54600, 0xc00032f500, 0xc0008b1500, 0xc0008f5bb0, 0x9, 0xc000710200)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/vendor/github.com/wal-g/storages/storage/folder.go:39 +0x183
github.com/wal-g/wal-g/internal.DeleteBeforeTarget(0x1c54600, 0xc00032f500, 0x1c42d00, 0xc000615f50, 0xc0004d6f00, 0xc0004d6fa0, 0xc0004d6fc0, 0xc000615f50, 0x0)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/internal/delete_handler.go:341 +0x196
github.com/wal-g/wal-g/internal.HandleDeleteRetain(0x1c54600, 0xc00032f500, 0xc0004d6b80, 0x1, 0x2, 0x0, 0xc0004d6fa0, 0xc0004d6fc0)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/internal/delete_handler.go:434 +0x186
github.com/wal-g/wal-g/cmd/mysql.runDeleteRetain(0x25dad40, 0xc0004d6b80, 0x1, 0x2)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/cmd/mysql/delete.go:67 +0x11c
github.com/spf13/cobra.(*Command).execute(0x25dad40, 0xc0004d6ae0, 0x2, 0x2, 0x25dad40, 0xc0004d6ae0)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x25d9940, 0x9e58ea, 0x25f3c60, 0xc000000180)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/mysql.Execute()
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/cmd/mysql/mysql.go:33 +0x31
main.main()
	/home/robot-pgaas-ci/workspace/wal-g-mysql-deb/src/github.com/wal-g/wal-g/main/mysql/main.go:8 +0x25
```

**Comment by reshke** [comment]
i will fix it someday just so as not to forget

**Comment by debebantur** [comment]
There was no repro for quite a while. I believe, this panic was fixed. I will close this issue for now, if there are any concerns left, feel free to reopen it
