### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by TheKigen** [wal-g/wal-g#885]
So lately I've noticed a random error in WAL-G.  This appears to be a threading issue (failure to mutex a variable).

This is a delta backup on a PostgreSQL 12 replica server.

```
Feb 18 04:00:10 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:10.417426 Delta backup from base_000000010000C75600000009_D_000000010000C727000000A9 with LSN c756093192d8.
Feb 18 04:00:10 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:10.436512 Calling pg_start_backup()
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.211905 Querying pg_database
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.229997 Querying pg_stat_all_tables
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.265302 Querying pg_stat_all_tables
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.297815 Querying pg_stat_all_tables
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.350984 Querying pg_stat_all_tables
Feb 18 04:00:11 db02-replica wal-g[3479]: INFO: 2021/02/18 04:00:11.372251 Walking ...
Feb 18 04:01:12 db02-replica wal-g[3479]: fatal error: concurrent map read and map write
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 86 [running]:
Feb 18 04:01:12 db02-replica wal-g[3479]: runtime.throw(0x2788313, 0x21)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0000dad60 sp=0xc0000dad30 pc=0xfb9fb2
Feb 18 04:01:12 db02-replica wal-g[3479]: runtime.mapaccess1(0x2459700, 0xc000b6a060, 0xc001d96ff0, 0xc000871068)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/runtime/map.go:411 +0x24f fp=0xc0000dada0 sp=0xc0000dad60 pc=0xf91f8f
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*PagedFileDeltaMap).GetDeltaBitmapFor(0xc0004c5c48, 0xc0004e6f60, 0x2d, 0x8000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/paged_file_delta_map.go:81 +0xad fp=0xc0000dae08 sp=0xc0000dada0 pc=0x2116e4d
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).getExpectedFileSize(0xc0004c5ba0, 0xc000b927c0, 0x2d, 0xc000113078, 0x1)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:268 +0x67 fp=0xc0000dae80 sp=0xc0000dae08 pc=0x21241c7
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFile(0xc0004c5ba0, 0xc000b927c0, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:215 +0x65 fp=0xc0000daf10 sp=0xc0000dae80 pc=0x2123985
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFileWorker(0xc0004c5ba0, 0xc000113020, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:205 +0x6d fp=0xc0000daf48 sp=0xc0000daf10 pc=0x21238ad
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.NewRatingTarBallComposer.func1(0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:136 +0x33 fp=0xc0000daf78 sp=0xc0000daf48 pc=0x2142493
Feb 18 04:01:12 db02-replica wal-g[3479]: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b6a030, 0xc000ae4650)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59 fp=0xc0000dafd0 sp=0xc0000daf78 pc=0x1e38599
Feb 18 04:01:12 db02-replica wal-g[3479]: runtime.goexit()
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000dafd8 sp=0xc0000dafd0 pc=0xff2041
Feb 18 04:01:12 db02-replica wal-g[3479]: created by golang.org/x/sync/errgroup.(*Group).Go
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 1 [runnable]:
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Syscall6(0x106, 0xffffffffffffff9c, 0xc00135a090, 0xc001752108, 0x100, 0x0, 0x0, 0x0, 0xc001752108, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.fstatat(0xffffffffffffff9c, 0xc00135a060, 0x2d, 0xc001752108, 0x100, 0x2d, 0xc00135a060)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1480 +0xc8
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Lstat(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/syscall_linux_amd64.go:73
Feb 18 04:01:12 db02-replica wal-g[3479]: os.lstatNolog(0xc00135a060, 0x2d, 0x2d, 0x1, 0xc00135a060, 0x2d)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/stat_unix.go:42 +0x6e
Feb 18 04:01:12 db02-replica wal-g[3479]: os.Lstat(0xc00135a060, 0x2d, 0x2, 0xc00135a060, 0x2d, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/stat.go:22 +0x4d
Feb 18 04:01:12 db02-replica wal-g[3479]: path/filepath.walk(0xc001349770, 0x28, 0x2a03060, 0xc0013d15f0, 0xc001bfd918, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/path/filepath/path.go:378 +0x1da
Feb 18 04:01:12 db02-replica wal-g[3479]: path/filepath.walk(0xc000b614c0, 0x20, 0x2a03060, 0xc000a18000, 0xc001bfd918, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/path/filepath/path.go:384 +0x2fe
Feb 18 04:01:12 db02-replica wal-g[3479]: path/filepath.walk(0xc0005a8420, 0x1b, 0x2a03060, 0xc0004c5c70, 0xc001bfd918, 0x0, 0xc00032c5e0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/path/filepath/path.go:384 +0x2fe
Feb 18 04:01:12 db02-replica wal-g[3479]: path/filepath.Walk(0xc0005a8420, 0x1b, 0xc000d4d918, 0x1, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/path/filepath/path.go:406 +0x105
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.createAndPushBackup(0xc00011bb90, 0xc0005a8420, 0x1b, 0x276c1b7, 0x10, 0xc00010f90b, 0x38, 0xc000cd85a8, 0xc000cd85d0, 0xc000cc42a0, ...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/backup_push_handler.go:131 +0x8ad
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.HandleBackupPush(0xc00011bb90, 0x7ffd04262ebc, 0x1b, 0x10000, 0x2)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/backup_push_handler.go:258 +0x285
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/cmd/pg.glob..func4(0x39c9060, 0xc000a55410, 0x1, 0x3)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/cmd/pg/backup_push.go:40 +0x10d
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/spf13/cobra.(*Command).execute(0x39c9060, 0xc000a553b0, 0x3, 0x3, 0x39c9060, 0xc000a553b0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/spf13/cobra.(*Command).ExecuteC(0x39c79e0, 0xfc99ea, 0x39e0ba0, 0xc000000180)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/spf13/cobra.(*Command).Execute(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/github.com/spf13/cobra/command.go:864
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/cmd/pg.Execute()
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/cmd/pg/pg.go:39 +0x31
Feb 18 04:01:12 db02-replica wal-g[3479]: main.main()
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/main/pg/main.go:8 +0x25
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 13 [select]:
Feb 18 04:01:12 db02-replica wal-g[3479]: go.opencensus.io/stats/view.(*worker).start(0xc0003c6690)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
Feb 18 04:01:12 db02-replica wal-g[3479]: created by go.opencensus.io/stats/view.init.0
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 87 [runnable]:
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Syscall(0x0, 0x9, 0xc000abe000, 0x2000, 0x2000, 0x2000, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.read(0x9, 0xc000abe000, 0x2000, 0x2000, 0x8, 0x29bd3c0, 0xc001784000)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/syscall_unix.go:187
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read.func1(0x7ffff800000, 0x2, 0xc0001b0f08)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x4c
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.ignoringEINTR(0xc000d53ac0, 0x72, 0x275f501, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:567 +0x27
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read(0xc0001b0f00, 0xc000abe000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x13e
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file_posix.go:31
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).Read(0xc001426ed0, 0xc000abe000, 0x2000, 0x2000, 0xf8cd9f, 0xc00003c000, 0x245f800)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file.go:116 +0x71
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadAtLeast(0x7f1c80191ad0, 0xc000aa8b10, 0xc000abe000, 0x2000, 0x2000, 0x2000, 0x2000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:314 +0x87
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadFull(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:333
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*IncrementalPageReader).FullScanInitialize(0xc000d53d18, 0xc000aa8b10, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/incremental_page_reader.go:120 +0xd0
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.ReadIncrementLocations(0xc0004e6960, 0x2e, 0x40000000, 0xc756093192d8, 0x7f1c803f6548, 0xc000d53e40, 0xf902f0, 0xc0003c6d70, 0x50)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/pagefile.go:151 +0x18a
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).scanDeltaMapFor(0xc0004c5ba0, 0xc0004e6960, 0x2e, 0x40000000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:286 +0x8b
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).getExpectedFileSize(0xc0004c5ba0, 0xc000780bc0, 0x2e, 0xc000113078, 0x1)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:263 +0x1f5
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFile(0xc0004c5ba0, 0xc000780bc0, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:215 +0x65
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFileWorker(0xc0004c5ba0, 0xc000113020, 0xc000600024, 0x27cc1d8)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:205 +0x6d
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.NewRatingTarBallComposer.func1(0xc000600000, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:136 +0x33
Feb 18 04:01:12 db02-replica wal-g[3479]: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b6a030, 0xc000ae4660)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
Feb 18 04:01:12 db02-replica wal-g[3479]: created by golang.org/x/sync/errgroup.(*Group).Go
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 88 [runnable]:
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Syscall(0x0, 0xf, 0xc001cae000, 0x2000, 0x2000, 0x2000, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.read(0xf, 0xc001cae000, 0x2000, 0x2000, 0x8, 0x29bd3c0, 0xc00170e000)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/syscall_unix.go:187
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read.func1(0x7ffff800000, 0x2, 0xc0003a7748)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x4c
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.ignoringEINTR(0xc000d01ac0, 0x72, 0x275f501, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:567 +0x27
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read(0xc0003a7740, 0xc001cae000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x13e
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file_posix.go:31
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).Read(0xc00011cd90, 0xc001cae000, 0x2000, 0x2000, 0xf8cd9f, 0xc00003c000, 0x245f800)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file.go:116 +0x71
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadAtLeast(0x7f1c80191ad0, 0xc0007e1590, 0xc001cae000, 0x2000, 0x2000, 0x2000, 0x2000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:314 +0x87
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadFull(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:333
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*IncrementalPageReader).FullScanInitialize(0xc000d01d18, 0xc0007e1590, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/incremental_page_reader.go:120 +0xd0
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.ReadIncrementLocations(0xc0004ef200, 0x31, 0x16354000, 0xc756093192d8, 0x8, 0xc000d01e40, 0xf902f0, 0xc0003c6e10, 0x50)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/pagefile.go:151 +0x18a
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).scanDeltaMapFor(0xc0004c5ba0, 0xc0004ef200, 0x31, 0x16354000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:286 +0x8b
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).getExpectedFileSize(0xc0004c5ba0, 0xc000780400, 0xc000c4e188, 0xc000113078, 0x1)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:263 +0x1f5
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFile(0xc0004c5ba0, 0xc000780400, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:215 +0x65
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFileWorker(0xc0004c5ba0, 0xc000113020, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:205 +0x6d
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.NewRatingTarBallComposer.func1(0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:136 +0x33
Feb 18 04:01:12 db02-replica wal-g[3479]: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b6a030, 0xc000ae4670)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
Feb 18 04:01:12 db02-replica wal-g[3479]: created by golang.org/x/sync/errgroup.(*Group).Go
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
Feb 18 04:01:12 db02-replica wal-g[3479]: goroutine 89 [runnable]:
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Syscall(0x0, 0x22, 0xc000f3e000, 0x2000, 0x2000, 0x2000, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.read(0x22, 0xc000f3e000, 0x2000, 0x2000, 0x8, 0x29bd3c0, 0xc0018c8000)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
Feb 18 04:01:12 db02-replica wal-g[3479]: syscall.Read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/syscall/syscall_unix.go:187
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read.func1(0x7ffff800000, 0x2, 0xc001003388)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x4c
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.ignoringEINTR(0xc000d05ac0, 0x72, 0x275f501, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:567 +0x27
Feb 18 04:01:12 db02-replica wal-g[3479]: internal/poll.(*FD).Read(0xc001003380, 0xc000f3e000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/internal/poll/fd_unix.go:155 +0x13e
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).read(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file_posix.go:31
Feb 18 04:01:12 db02-replica wal-g[3479]: os.(*File).Read(0xc0007bbc30, 0xc000f3e000, 0x2000, 0x2000, 0xf8cd9f, 0xc00003c000, 0x245f800)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/os/file.go:116 +0x71
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadAtLeast(0x7f1c80191ad0, 0xc000f3c030, 0xc000f3e000, 0x2000, 0x2000, 0x2000, 0x2000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:314 +0x87
Feb 18 04:01:12 db02-replica wal-g[3479]: io.ReadFull(...)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/usr/local/go/src/io/io.go:333
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*IncrementalPageReader).FullScanInitialize(0xc000d05d18, 0xc000f3c030, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/incremental_page_reader.go:120 +0xd0
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.ReadIncrementLocations(0xc001348870, 0x2d, 0x56000, 0xc756093192d8, 0x8, 0xc000d05e40, 0xf902f0, 0xc001ad0780, 0x50)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/pagefile.go:151 +0x18a
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).scanDeltaMapFor(0xc0004c5ba0, 0xc001348870, 0x2d, 0x56000, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:286 +0x8b
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).getExpectedFileSize(0xc0004c5ba0, 0xc000780f80, 0xc000c4e180, 0xc000113078, 0x1)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:263 +0x1f5
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFile(0xc0004c5ba0, 0xc000780f80, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:215 +0x65
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.(*RatingTarBallComposer).addFileWorker(0xc0004c5ba0, 0xc000113020, 0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:205 +0x6d
Feb 18 04:01:12 db02-replica wal-g[3479]: github.com/wal-g/wal-g/internal.NewRatingTarBallComposer.func1(0x0, 0x0)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/internal/rating_tar_ball_composer.go:136 +0x33
Feb 18 04:01:12 db02-replica wal-g[3479]: golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b6a030, 0xc000ae4680)
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59
Feb 18 04:01:12 db02-replica wal-g[3479]: created by golang.org/x/sync/errgroup.(*Group).Go
Feb 18 04:01:12 db02-replica wal-g[3479]: #011/vagrant/wal-g/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

.walg.json (relevant portions)
```
    "WALG_UPLOAD_DISK_CONCURRENCY": 4,
    "WALG_UPLOAD_CONCURRENCY": 6,
    "WALG_DELTA_MAX_STEPS": 14,
    "WALG_DELTA_ORIGIN": "LATEST",
    "WALG_COMPRESSION_METHOD": "brotli",
    "WALG_SKIP_REDUNDANT_TARS": "true",
    "WALG_TAR_SIZE_THRESHOLD": 2147483647,
    "WALG_USE_RATING_COMPOSER": "true",
    "WALG_USE_REVERSE_UNPACK": "true",
    "PGDATA": "/var/lib/postgresql/12/main",
    "PGHOST": "/var/run/postgresql"
```

**Comment by x4m** [comment]
Thanks for the report. It's apparently a concurrency bug.
PagedFileDeltaMap.GetDeltaBitmapFor() is not prepared for cuncurrent use, but rating composer is using it concurrently.
@usernamedt can you please take a look at it eventually?
PagedFileDeltaMap is a cache that can trigger concurrent write of the same element. Probably we could convert it to SyncMap or something like that.

**Comment by x4m** [comment]
The bug has no dramatic impact, the worst that can happen is one cache entry may be loaded multiple times. Though failed cron backup is clearly not a nice thing.

**Comment by usernamedt** [comment]
@x4m ok, I'll look into this
