### ISSUE TITLE
Error when gpg key provided and key does not exists

### ISSUE THREAD

**Issue by proggga** [wal-g/wal-g#980]
### Database name
Found at Redis, but can be everywhere

# Issue description

### Describe your problem
I provided GPG key for backup-push and wal-g fails with stacktrace

```bash
./main/redis/wal-g backup-push --walg-file-prefix tmp --walg-stream-create-command 'redis-cli --rdb /dev/stdout' --walg-sentinel-user-data '{"shard":"debug_redis"}'  --walg-gpg-key-id="hello there"
WARNING: 2021/05/17 20:02:21.491191 You are using deprecated functionality that uses an external gpg library.
It will be removed in next major version.
Please set GPG key using environment variables WALG_PGP_KEY or WALG_PGP_KEY_PATH.
INFO: 2021/05/17 20:02:21.510091 Removing sigmask. Shutting down
panic: Got error while exporting gpg key: 'gpg: WARNING: nothing exported'

goroutine 1 [running]:
github.com/wal-g/wal-g/internal.CompressAndEncrypt(0x575b900, 0xc00000e5d0, 0x57756c0, 0x65104f0, 0x5773be0, 0xc00054a000, 0x1f, 0x5524fdd)
	/Users/mkfesenko/work/wal-g/internal/compress_and_encrypt.go:39 +0x368
github.com/wal-g/wal-g/internal.(*Uploader).PushStreamToDestination(0xc0003ae420, 0x575b900, 0xc00000e5d0, 0xc00005e120, 0x22, 0x22, 0x17)
	/Users/mkfesenko/work/wal-g/internal/stream_push_helper.go:32 +0xa6
github.com/wal-g/wal-g/internal.(*Uploader).PushStream(0xc0003ae420, 0x576b6c0, 0xc000120000, 0xc00003c000, 0x526e1e0, 0x54f1380, 0x576b6c0)
	/Users/mkfesenko/work/wal-g/internal/stream_push_helper.go:21 +0x108
github.com/wal-g/wal-g/internal/databases/redis/archive.(*StorageUploader).UploadBackup(0xc000534170, 0x576b6c0, 0xc000120000, 0x576b740, 0xc0002511e0, 0x577c338, 0xc0003c2100, 0x0, 0xc000b3fc88)
	/Users/mkfesenko/work/wal-g/internal/databases/redis/archive/backup.go:123 +0x10b
github.com/wal-g/wal-g/internal/databases/redis.HandleBackupPush(0xc0003ae420, 0xc0002511e0, 0x577c338, 0xc0003c2100, 0xc0002511e0, 0x0)
	/Users/mkfesenko/work/wal-g/internal/databases/redis/backup_push_handler.go:18 +0x16e
github.com/wal-g/wal-g/cmd/redis.glob..func3(0x64c5b00, 0xc00022e2a0, 0x0, 0x7)
	/Users/mkfesenko/work/wal-g/cmd/redis/backup_push.go:47 +0x2b1
github.com/spf13/cobra.(*Command).execute(0x64c5b00, 0xc00022e230, 0x7, 0x7, 0x64c5b00, 0xc00022e230)
	/Users/mkfesenko/work/wal-g/vendor/github.com/spf13/cobra/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x64c5d80, 0xc000000180, 0x200000003, 0xc000000180)
	/Users/mkfesenko/work/wal-g/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mkfesenko/work/wal-g/vendor/github.com/spf13/cobra/command.go:864
github.com/wal-g/wal-g/cmd/redis.Execute()
	/Users/mkfesenko/work/wal-g/cmd/redis/redis.go:33 +0x31
main.main()
	/Users/mkfesenko/work/wal-g/main/redis/main.go:8 +0x25
```

**Comment by viggy28** [comment]
FWIW, I export `WALG_PGP_KEY_PATH` with the location of the PGP key stored in ASCII format and it works.

**Comment by proggga** [comment]
> FWIW, I export `WALG_PGP_KEY_PATH` with the location of the PGP key stored in ASCII format and it works.

I’ve provided GPG not PGP without path, you can see args  and Params first line in log provided above
